let theo_vortaro = `ก
กรุณา bonvolu
ก้นบึ้ง fundo
กระจ่าง/ใส klara
กระดาน tabulo
กระดาษ papero
กระดุม/ปุ่ม butono
กระโดด salti
กระเป๋า (เสื้อ/กางเกง) poŝo
กระเป๋าถือ mansako
กระโปรง jupo
กับ kun
กริ๊ง/กังวาน sonori
กลัว timi
กลางคืน nokto
กว่า ol
กวาด balai
ก้อนหิน ŝtono
กางเกงขายาว pantalono
กาแฟ kafo
การเดินทาง/การท่องเที่ยว ekskurso
การทักทาย saluto
การเฝ้าดู/เอาใจใส่ atenti
การเริ่มต้น komenco
การแลกเปลี่ยน interŝanĝi
กําแพง/ฝาผนัง muro
กิ่งไม้ branĉo
กิน manĝi
กิโลกรัม kilogramo
กิโลเมตร kilometro
กึ่งกลาง mezo
เก็บเกี่ยว rikolti
เก่า/แก่ aĝa
เก้า naŭ
เก้าอี้ seĝo
เก้าอี้มีที่วางแขน fotelo
เกิด/กําเนิด naskiĝi
เกิดขึ้น okazi
เกี่ยวกับ pri
เกี่ยวกับต่างประเทศ fremda
เกือบจะ preskaŭ
แก้ม vango
แก้ว (วัตถุ)/กระจก vitro
แก้ว/ถ้วยแก้ว glaso
แกะ ŝafo
ใกล้ๆ proksima
ไก่ตัวผู้ koko
ไกลออกไป for
ข
ขนมเค้ก kuko
ขนมปัง pano
ขวด botelo
ขวา dekstra
ขว้าง/ปา ĵeti
ของ (ปริมาณ) da
ของเขา/ของมัน/ของพวกเขา sia
ของเขาเอง propra
ของใคร kies
ขอบใจ danki
ขอร้อง peti
ขา kruro
ข้าง/ด้าน flanko
ข้างนอก/ภายนอก (คําวิเศษณ์) ekstere
ข้างนอก/ภายนอก ekster
ข้างหน้า/ก่อน antaŭ
ข้างๆ/ถัดไป/ต่อไป apud
ข้าม trans
ขาย vendi
เขา (ผู้ชาย) li
เขา (ผู้หญิง) ŝi
เข้าใจ kompreni
เขียน skribi
แขก/ผู้มาหา gasto
แข็งแรง forta
แขน brako
ไข่ ovo
ค
คณิตศาสตร์ matematiko
คน/มนุษย์ homo
คนใดคนหนึ่ง/สิ่งใดสิ่งหนึ่ง iu
คนใดคนหนึ่ง/หรือคนทั่วไป oni
ครอบครัว familio
ครั้งหนึ่ง/เคย foje
ความโกรธ kolero
ความจริง vero
ความตาย morto
ความปรารถนา deziri
ความอยากอาหาร apetito
คอ kolo
คาง mentono
ค้าง/อยู่ต่อ resti
คําขึ้นต้นประโยคคําถามที่ตอบ “ ใช่ ” หรือ “ ไม่ใช ่” ĉu
คํานําหน้าที่แสดงถึงความเป็นตรงกันข้าม mal-
คําสั่ง ordo
คิด pensi
คุณ vi
คุณสมบัติ/คุณลักษณะ kvalito
คุยกันสนุกๆ babili
คู่ paro
คู่หมั้นชาย fianĉo
เครื่องจักร maŝino
เครื่องใช้ไฟฟ้า elektra
เคาะ frapi
โคมไฟ lampo
ง
ง่าย facila
ง่าย/ธรรมดา simpla
เงา/ร่มเงา ombro
เงิน mono
เงินบาท bahto (taja mono)
งี่เง่า/โง่ stulta
เงียบ silenti
จ
จดหมาย letero
จนกระทั่ง/ถึง ĝis
จมูก nazo
จักรยาน biciklo
จับ/ได้รับ kapti
จาก/ขอ de
จาน telero
จ่าย pagi
จํา memori
จํานวนนั้น/ปริมาณนั้น tiom
จําเป็น bezoni
จูบ kiso
เจ็ด sep
เจ็บปวด dolori
แจกัน vazo
ใจดีในการที่ bonvoli
ฉ
ฉัน mi
เฉลียวฉลาด/มีปัญญา saĝa
ช
ชนิดใด kia
ชนิดใดชนิดหนึ่ง ia
ช่วยเหลือ helpi
ช็อคโกแลต ĉokolado
ช้อน kulero
ชอบ ŝati
ชอล์ก kreto
ชั้นของอาคาร etaĝo
ชั้นเรียน klaso
ชั่วโมง horo
ชายฝั่ง bordo
ชายโสด fraŭlo
ชิ้น peco
ชื่อ nomo
ชุดผู้หญิง robo
เช่นนั้น/แบบนั้น tia
เชื่อ kredi
ใช่ jes
ใช้ uzi
ซ
ซ่อน kaŝi
ซักเวลาหนึ่ง iam
ซึ่ง ke
ซื้อ aĉeti
ซุป supo
ญ
ญาติ parenco
ด
ดนตรี muziko
ดวงจันทร์ luno
ดวงดาว stelo
ดวงตราไปรษณีย์ poŝtmarko
ดวงตา okulo
ดวงอาทิตย์ suno
ด้วย ankaŭ
ด้วยตัวเอง mem
ด้วยเหตุนั้น tial
ดอกกุหลาบ rozo
ดอกไม้ floro
ดัง laŭta
ดังนั้น tiel
ดังนั้น do
ดํารงอยู่ farti
ดินสอ krajono
ดี bona
ดึง/ลาก tiri
ดื่ม trinki
ดูด/ดูดนม suĉi
ดูแล zorgi
ดูสิ! jen
ดูเหมือน/ดูเหมือนว่า/ราวกับ aspekti
เด็ก infano
เด็กผู้ชาย knabo
เด็กอ่อน bebo
เดินทางด้วยยานพาหนะ veturi
เดี๋ยวนี้ nun
เดือน monato
เดือนกรกฎาคม julio
เดือนกันยายน septembro
เดือนกุมภาพันธ์ februaro
เดือนตุลาคม oktobro
เดือนธันวาคม decembro
เดือนพฤศจิกายน novembro
เดือนพฤษภาคม majo
เดือนมกราคม januaro
เดือนมิถุนายน junio
เดือนมีนาคม marto
เดือนเมษายน aprilo
เดือนสิงหาคม aŭgusto
โดดเดี่ยว sola
โดย (เครื่องมือ) per
ได้ยิน aŭdi
ได้รับ ricevi
ต
ตก fali
ต้นไม้ arbo
ตรงกันข้าม/ต้าน kontraŭ
ต่อกัน/เข้าร่วม aliĝi
ต้อง devi
ต้องการ voli
ตอนเช้า mateno
ตอนเย็น vespero
ตอบ respondi
ตะกร้าซื้อของ korbo
ตะโกน krii
ตัด (ด้วยกรรไกร) tondi
ตัด (ด้วยมีด) tranĉi
ตัดสินใจ decidi
ตั๋ว bileto
ตัวเขาเอง/ตัวพวกเขาเอง si
ต่างๆ diversaj
ตาม/ตามแต่/ที่กําหนดโดย laŭ
ติดต่อทางจดหมาย korespondi
ติดตาม/ทําตาม sekvi
ตู้ใส่ของ/ห้องเล็ก ŝranko
เต้นรํา danci
เต็ม plena
เตรียม prepari
เตาอบ forno
เติบโต kreski
เตียงนอน lito
แต่ sed
แต่กระนั้นก็ตาม/อย่างไรก็ดี tamen
แต่แรก/แต่เช้า/เร็ว frua
แต่ละ/ต่อ po
โต๊ะ tablo
ใต้ sub
ถ
ถนน strato
ถนน/ทางเดิน vojo
ถ้วย taso
ถ้า se
ถาม demandi
ถือ/ขน/บรรทุก porti
ถุงเท้า ŝtrumpo
แถว vico
ท
ทหาร soldato
ท้อง ventro
ท่องเที่ยว/เดินทาง vojaĝi
ท้องฟ้า ĉielo
ทะเล maro
ทั้งสอง/ทั้งคู่ ambaŭ
ทั้งหมด tuta
ทั้ง ๆที่ malgraŭ
ทํา fari
ทํางาน labori
ทําผิดพลาด erari
ทําไม kial
ทําให้สมบูรณ์ kompletigi
ทิศใต้ sudo
ที่ je
ที่ ĉe
ที่นั้น tie
ที่รัก kara
ที่สอง sekundo
ที่ไหน kie
ที่อยู่ adreso
ทุก ĉiu
ทุกชนิด ĉia
ทุกสิ่ง ĉio
ทุกแห่ง ĉie
ทุ่ง/นา/สนาม kampo
เท้า piedo
เท่านั้น/เพียงแค่ nur
เท่าไหร่ kiom
แท้จริง/ถูกต้อง pravi
แทนที่ anstataŭ
แทบจะไม่ apenaŭ
โทรทัศน์ televido
ธ
ธรรมชาติ naturo
น
นก birdo
นม lakto
นวนิยาย romano
นอกจากนั้น krom
นอน (ลง) kuŝi
นอนหลับ dormi
นักประพันธ์/ผู้เขียน aŭtoro
นักเรียน/นักศึกษา studento
นั่ง sidi
นั้น tio
เมา ebria
เมื่อ/เมื่อไร kiam
เมือง urbo
เมื่อวาน hieraŭ
แม่น้ํา rivero
แม้แต่ eĉ
แม้ว่า kvankam
แมว kato
ไม่ ne
ไม่เคย neniam
ไม่ใช่ชนิดใด nenia
ไม่ และไม่ nek
ไม่มี/ขาด/ไร้ manki
ไม่มีใคร/ไม่มีอะไร neniu
ไม่มีที่ไหนเลย nenie
ไม่มีสิ่งใด nenio
ย
ยกโทษให้ pardoni
ยังคง ankoraŭ
ย่าน (ของเมือง) kvartalo
ยาว longa
ยิง pafi
ยินดี/ดีใจ ĝoji
ยืน stari
ยืม prunti
เย็บ kudri
เยี่ยมเยียน viziti
เยื่อบาง/ฟิล์ม/ภาพยนตร์ filmo
ร
รถแทรกเตอร์ traktoro
รถประจําทาง aŭtobuso
รถยนต์ aŭto
รถราง tramo
รบกวน/ทําให้รําคาญ ĝeni
รสชาติ gusto
รอคอย atendi
รองเท้า ŝuo
ร้องเพลง kanti
ร้องไห้ plori
รอบ ĉirkaŭ
ระหว่าง inter
รัก ami
รัฐ ŝtato
ร่าเริง/เบิกบานใจ gaja
ราคา kosti
ร่างกาย korpo
ร้านค้า magazeno
ราวกับ kvazaŭ
ร่ํารวย riĉa
รู้ scii
รู้จัก/คุ้นเคยกับ koni
รูปภาพ bildo
รู้สึก senti
เรียก voki
เรียนรู้/เรียน lerni
เรือ ŝipo
เรื่องราว anekdoto
โรงงาน fabriko
โรงละคร teatro
โรงภาพยนตร์ kinejo
โรงแรม hotelo
ฤ
ฤดูกาล sezono
ฤดูร้อน somero
ฤดูหนาว vintro
ฤดูใบไม้ผลิ printempo
ฤดูใบไม้ร่วง aŭtuno
ล
ลงโทษ puni
ลม vento
ลา (ชื่อสัตว์ชนิดหนึ่ง) azeno
ล้าง/ซัก lavi
ลําต้น/ลําตัว trunko
ลิตร litro
ลิ้น lango
ลืม forgesi
ลุกขึ้น/ขึ้น leviĝi
ลุง/อา onklo
ลูกชาย filo
ลูกบอล pilko
ลูกพลัม pruno
ลูกพี่ลูกน้อง kuzo
ลูกแพร์ piro
ลูกอม bombono
ลูบเบาๆ ด้วยความรัก karesi
เล็กมาก eta
เล่น ludi
เล่นสกี skii
เลยไป/พ้น preter
แล้ว jam
และ kaj
โลก (เชิงสังคม) mondo
โลก (ทางกายภาพ) tero
ว
วัด/ชั่ง mezuri
วัตถุ/สิ่งของ objekto
วัน tago
วันจันทร์ lundo
วันที่ dato
วันนี้ hodiaŭ
วันพฤหัสบดี ĵaŭdo
วันพุธ merkredo
วันศุกร์ vendredo
วันสําคัญทางศาสนา/เทศกาล festo
วันเสาร์ sabato
วันหยุด ferioj
วันอังคาร mardo
วันอาทิตย์ dimanĉo
วัวตัวเมีย bovino
วาง/ใส่ meti
วาด desegni
ว่ายน้ํา naĝi
วิ่ง kuri
วิทยุ radioaparato
วิพากษ์วิจารณ์ kritiki
เวลา tempo
เวลาครู่เดียว momento
เวลานั้น tiam
ไวน์ vino
ไวยากรณ์ gramatiko
ศ
ศีรษะ kapo
ส
ส่ง sendi
สด/ใหม่ freŝa
สตรอเบอรี่ frago
สถานที่ loko
สถานี stacio
สมาชิก membro
สมาชิก ano
สภาพอากาศ vetero
สมัยใหม่/ทันสมัย moderna
สลับซับซ้อน komplika
สวน ĝardeno
สวนสัตว์ zoologia
ส่วน parto

นาที minuto
น่าพึงพอใจ agrable
น่ารัก/สวย bela
น่าสนใจ interesa
น่าเสียใจ bedaŭri
นาย sinjoro
นาฬิกา horloĝo
น้ํา akvo
น้ําตาล sukero
น้ําผึ้ง mielo
นําเสนอ prezenti
นิตยสาร gazeto
นิยาย fabelo
นิ้วมือ fingro
นี้/อันนี้/คนนี้ ĉi
เนคไท kravato
เนยแข็ง fromaĝo
เนยอ่อน butero
เนื้อสัตว์ viando
เนื่องมาจาก pro
ใน en
ในไม่ช้า baldaŭ
ในระหว่างที่ dum
บ
บท/บทเรียน leciono
บน sur
บริเวณหน้าบ้าน korto
บอก/พูด diri
บอก/เล่า rakonti
บ่อยๆ ofte
บ้าง/จํานวนหนึ่ง iom
บ้าน hejmo
บ้าน domo
บิน flugi
บุคคล persono
บุหรี่ cigaredo
เบียร์ biero
แบบเดียวกัน same
โบกี้รถไฟ vagono
โบสถ์ preĝejo
ใบไม้ folio
ใบหน้า vizaĝo
ป
ปฏิทิน kalendaro
ประตู pordo
ประเทศ lando
ประเทศเวียดนาม Vjetnamio
ประเทศไทย Tajlando
ประวัติศาสตร์ historio
ประโยค frazo
ปรากฏ aperi
ปราศจาก sen
ปรุงอาหาร kuiri
ปล่อยแสง/เปล่งแสงออกมา lumi
ปลา fiŝo
ปลาย/ตอนจบ fino
ปลุกให้ตื่น veki
ปัญหา problemo
ปาก buŝo
ปากกา plumo
ปิด fermi
ปี jaro
ปีอธิกสุรทิน6 วัน superjaro
ปู่ หรือ ตา avo
เป็น/อยู่/คือ esti
เป็นที่พอใจ/ที่ชอบ plaĉi
เป็นเรื่องที่พูดคุย afero
เปลวไฟ flamo
เป่า blovi
เป่านกหวีด/ผิวปาก fajfi
แป้งทําอาหาร faruno
แปด ok
ไป iri
ไปเดินเล่น promeni
ไปถึง al
ไปรษณียบัตรรูปภาพ bildkarto
ผ
ผม/ขน haro
ผลเชอรี่ ĉerizo
ผลไม้ frukto
ผลไม้กวน/แยมผลไม้ marmelado
ผลัก/ดัน puŝi
ผัก legomo
ผักกะหล่ํา brasiko
ผ้าหรือกระดาษเช็ดปาก buŝtuko
ผ่าน/ผ่านทะลุ tra
ผ่าน pasi
ผ้าปูโต๊ะ tablotuko
ผึ้ง abelo
ผู้ชาย viro
ผู้นํา ĉefo
ผู้นํา/หัวหน้า estro
ผู้อํานวยการ direktoro
เผา/ไหม้ bruli
เผา (เหล็ก) forĝi
แผง stalo
ฝ
ฝน pluvo
พ
พบ renkonti
พร้อม/เสร็จ preta
พระราชา reĝo
พรุ่งนี้ morgaŭ
พวกเขา ili
พวกเรา ni
พ่อ patro
พ่อม่าย vidvo
พักผ่อน ripozi
พัน (จํานวน) mil
พี่ชาย หรือ น้องชาย frato
พืช planto
พื้น planko
พูด paroli
เพชร diamanto
เพดาน plafono
เพราะว่า ĉar
เพิ่งจะ ĵus
เพียงพอ sufiĉe
เพื่อที่ว่า por
เพื่อน amiko
แพะ kapro
ฟ
ฟัง aŭskulti
ฟัน dento
ไฟ fajro
ภ
ภัตตาคาร/ร้านอาหาร restoracio
ภาษา lingvo
ภาษาเวียดนาม vjetnama
ภาษาไทย taja
ภูเขา monto
ภูมิศาสตร์ geografio
ม
มองดู rigardi
มองหา serĉi
มองเห็น vidi
มะนาว citrono
มัน ĝi
มันฝรั่ง terpomo
มา veni
ม้า ĉevalo
มาก/อย่างยิ่ง tre
มาก multaj
มากกว่า pli
มากเกินไป tro
มากขึ้น/เพิ่มขึ้น plu
มากที่สุด plej
ม้านั่งยาว benko
มี havi
มีชีวิตอยู่ vivi
มีแนวโน้ม ema
มือ mano
เมฆ nubo
เมา ebria
เมื่อ/เมื่อไร kiam
เมือง urbo
เมื่อวาน hieraŭ
แม่น้ํา rivero
แม้แต่ eĉ
แม้ว่า kvankam
แมว kato
ไม่ ne
ไม่เคย neniam
ไม่ใช่ชนิดใด nenia
ไม่ และไม่ nek
ไม่มี/ขาด/ไร้ manki
ไม่มีใคร/ไม่มีอะไร neniu
ไม่มีที่ไหนเลย nenie
ไม่มีสิ่งใด nenio
ย
ยกโทษให้ pardoni
ยังคง ankoraŭ
ย่าน (ของเมือง) kvartalo
ยาว longa
ยิง pafi
ยินดี/ดีใจ ĝoji
ยืน stari
ยืม prunti
เย็บ kudri
เยี่ยมเยียน viziti
เยื่อบาง/ฟิล์ม/ภาพยนตร์ filmo
ร
รถแทรกเตอร์ traktoro
รถประจําทาง aŭtobuso
รถยนต์ aŭto
รถราง tramo
รบกวน/ทําให้รําคาญ ĝeni
รสชาติ gusto
รอคอย atendi
รองเท้า ŝuo
ร้องเพลง kanti
ร้องไห้ plori
รอบ ĉirkaŭ
ระหว่าง inter
รัก ami
รัฐ ŝtato
ร่าเริง/เบิกบานใจ gaja
ราคา kosti
ร่างกาย korpo
ร้านค้า magazeno
ราวกับ kvazaŭ
ร่ํารวย riĉa
รู้ scii
รู้จัก/คุ้นเคยกับ koni
รูปภาพ bildo
รู้สึก senti
เรียก voki
เรียนรู้/เรียน lerni
เรือ ŝipo
เรื่องราว anekdoto
โรงงาน fabriko
โรงละคร teatro
โรงภาพยนตร์ kinejo
โรงแรม hotelo
ฤ
ฤดูกาล sezono
ฤดูร้อน somero
ฤดูหนาว vintro
ฤดูใบไม้ผลิ printempo
ฤดูใบไม้ร่วง aŭtuno
ล
ลงโทษ puni
ลม vento
ลา (ชื่อสัตว์ชนิดหนึ่ง) azeno
ล้าง/ซัก lavi
ลําต้น/ลําตัว trunko
ลิตร litro
ลิ้น lango
ลืม forgesi
ลุกขึ้น/ขึ้น leviĝi
ลุง/อา onklo
ลูกชาย filo
ลูกบอล pilko
ลูกพลัม pruno
ลูกพี่ลูกน้อง kuzo
ลูกแพร์ piro
ลูกอม bombono
ลูบเบาๆ ด้วยความรัก karesi
เล็กมาก eta
เล่น ludi
เล่นสกี skii
เลยไป/พ้น preter
แล้ว jam
และ kaj
โลก (เชิงสังคม) mondo
โลก (ทางกายภาพ) tero
ว
วัด/ชั่ง mezuri
วัตถุ/สิ่งของ objekto
วัน tago
วันจันทร์ lundo
วันที่ dato
วันนี้ hodiaŭ
วันพฤหัสบดี ĵaŭdo
วันพุธ merkredo
วันศุกร์ vendredo
วันสําคัญทางศาสนา/เทศกาล festo
วันเสาร์ sabato
วันหยุด ferioj
วันอังคาร mardo
วันอาทิตย์ dimanĉo
วัวตัวเมีย bovino
วาง/ใส่ meti
วาด desegni
ว่ายน้ํา naĝi
วิ่ง kuri
วิทยุ radioaparato
วิพากษ์วิจารณ์ kritiki
วิภัตติซึ่งแสดงถึงการกระทํา
ที่ต่อเนื่อง -ant-
วิภัตติซึ่งแสดงว่าเป็นสิ่งของ
หรือวัตถุ -aĵ-17
เวลา tempo
เวลาครู่เดียว momento
เวลานั้น tiam
ไวน์ vino
ไวยากรณ์ gramatiko
ศ
ศีรษะ kapo
ส
ส่ง sendi
สด/ใหม่ freŝa
สตรอเบอรี่ frago
สถานที่ loko
สถานี stacio
สภาพอากาศ vetero
ส้อม forko
สะสม/เก็บ kolekti
สะอาด pura
สังเกตเห็น rimarki
สัตว์ (ไม่รวมมนุษย์) besto
สัตว์ animalo
สัปดาห์ semajno
สาม tri
สามารถ povi
สามี edzo
สําคัญ grava
สําหรับ/เพื่อ por
สิ่งของ/สิ่งต่างๆ aĵo
สิ่งใดสิ่งหนึ่ง io
สิงโต leono
สิ่งนั้น/คนนั้น tiu
สิบ dek
สี koloro
สี่ kvar
สีขาว blanka
สีเขียว verda
สีดํา nigra
สีแดง ruĝa
สีเทา griza
สีน้ําตาล bruna
สีฟ้า blua
สีเหลือง flava
สุก/บรรลุภาวะ matura
สุกร porko
สุขภาพดี sana
สุขสบาย feliĉa
สุนัข hundo
สุนัขป่า lupo
สุภาษิต proverbo
สูง alta
สูบบุหรี่ fumi
เส้นขอบฟ้า horizonto
เสมอ ĉiam
เสียง (ที่ใช้พูด) voĉo
เสือ tigro
เสื้อแจ็คเก็ต jako
เสื้อเชิ้ต ĉemizo
เสื้อนอก/เสื้อโค้ท mantelo
เสื้อผ้า vesto
เสื้อสตรีแค่เอวหลวมๆ bluzo
เสื้อไหมพรมสวมทางศีรษะ pulovero
แสงสว่าง hela
แสดง/โชว์ montri
ใส่กุญแจ ŝlosi
ห
หก ses
หญ้า herbo
หนังสือ libro
หลัก/สําคัญ ĉefa
หน้าต่าง fenestro
หน้าในหนังสือ paĝo
หน้าผาก frunto
หน้าอก brusto
หนึ่ง unu
หนึ่งร้อย cent
หนู muso
หมวกแก็ป ĉapo
หมู่บ้าน vilaĝo
หยุด halti
หยุด ĉesi
หรือ aŭ
หลัง/หลังจาก post
หลัง dorso
หลานชาย (ลูกชายของลูก) nepo
หลาย(มากกว่าหนึ่งสิ่งแต่ไม่
มากนัก) kelkaj
หวัง/ความหวัง espero
หวาน dolĉa
หว่าน semi
หวี kombi
ห่อ/หีบห่อ pakaĵo
ห้อง ĉambro
หอสูง/หอคอย turo
หัวใจ koro
หัวเราะ ridi
ห้า kvin
หาพบ trovi
หายใจ spiri
หิมะ neĝo
หู orelo
เห็ด fungo
เห็นแก่ตัว egoista
เหนือกว่า/เหนือ super
เหนื่อย laca
เห่า boji
แห้ง seka
แห่งชาติอังกฤษ angla
แห่งใดแห่งหนึ่ง ie
ให้/อนุญาตให้/ปล่อย lasi
ให้ doni
ใหญ่ granda
ใหญ่มาก ega
ใหม่ nova
ไหล/ลอย flui
อ
อนุญาต permesi
อเมริกา Ameriko
อย่างน้อย almenaŭ
อย่างเป็นมิตร afable
อย่างรวดเร็ว rapide
อย่างไร kiel
ออกจาก el
อ่อนเยาว์ juna
ออมเงิน ŝpari
อะไร kio
อะไรก็ได้ ajn
อันไหน/คนไหน kiu
อากาศ aero
อาจเป็นได้/บางที eble
อ่าน legi
อาบน้ํา bani
อายุ aĝo
อาศัยอยู่ loĝi
อิ่ม sata
อิสระ libera
อื่น/อื่นๆ alia
อุ่น varma
อุปกรณ์ หรือ เครื่องมือ ilo
อุโมงค์ tunelo
เอาไป preni
แอปเปิ้ล pomo
แอลกอฮอล์ alkoholo
ไอศกรีม glaciaĵo
--
กฏ/ข้อบังคับ leĝo
กฏหมาย juro
กระทันหัน subite
กระเทียม ajlo
กระเป๋าเดินทาง valizo
กว้าง larĝa
กลืน gluti
กลุ่ม grupo
ก๋วยเตี๋ยว/บะหมี่ nudelo
การค้า/การแลกเปลี่ยน komerco
การจราจร trafiko
การท่องเที่ยว turismo
การมีส่วนร่วม participi
กําไร profito
กีฬา sporto
เกษตรกรรม agrikulturo
เกลือ salo
แกง kareo
แก้ม vango
แก๊ส gaso
ขนส่ง liveri
ขยะ rubo
ขยัน/หมั่นเพียร diligenta
ข้อความ mesaĝo
ข้าว rizo
คลอง kanalo
คล่องแคล่ว/กระฉับกระเฉง vigla
ความคิด ideo
ความคิดเห็น opinio
ความถูกต้อง justeco
ความลับ sekreto
ความสัมพันธ์ rilato
ค่าธรรมเนียม kotizo
คําเชิญ invito
คุ้มครอง/ปกป้อง gardi
เคร่งขรึม/จริงจัง serioza
เครื่องเงิน arĝento
เครื่องเทศ spico
เครื่องแบบ uniformo
เงา ombro
เงินเดือน salajro
จักรราศี zodiako
จังหวัด provinco
จุดศูนย์กลาง centro
เจ็บปวด doloro
เจ้าชาย princo
ฉลาด inteligenta
ชกมวย boksi
ชอบมากกว่า preferi
ชัยชนะ venki
ช้าง elefanto
ชายแดน/เขตแดน limo
ชายหาด plaĝo
ชื่นชม admiri
เชื่อฟัง obei
เชือก ŝnuro
ซอกแซก zigzaga
ซอส saŭco
ซิป zipo
โซ่/ตรวน ĉeno
ดอกมะลิ jasmeno
โดยอัตโนมัติ aŭtomata
ตลาด merkato
ตั้งครรภ์ graveda
ตัวอักษร litero
ตาบอด blinda
ตํานาน legendo
ตําแหน่ง ofico
ตํารวจ polico
ติดกาว gluo
แตงกวา kukumo
ถั่วชนิดต่างๆ nukso
ถือสิทธิ/โมเม pretendi
ทดสอบ gusto
ทองคํา oro
ทะเลสาบ lago
ทันทีทันใด tuj
ทําให้ติดเชื้อ infekti
ทําให้โกรธเคือง ofendi
ทิศตะวันตก okcidento
ทิศตะวันออก oriento
ทิศเหนือ nordo
โทรศัพท์ televido
ธง flago
ธนาคาร banko
นวด masaĝo
น่ากลัว terura
นําทาง/นําเที่ยว gvidi
น้ําท่วม inundo
น้ําผลไม้ suko
น้ํามัน oleo
แน่นอน certa
บทในหนังสือ ĉapitro
บริษัท kompanio
แบ่ง/หาร dividi
ปกปิด kovri
ปฏิเสธ/ทางลบ negativa
ประชาชน/ผู้คน popolo
ประเทศชาติ nacio
ประหลาดใจ surprizo
ปล่อยกลิ่น odori
ป้องกัน protekti
เป็ด anaso
เป็นกลาง/เกียร์ว่าง neŭtrala
เป็นตัวแทน reprezenti
เป็นเจ้าของ posedi
เป็นพิธีการ formala
เปลี่ยน/แลก ŝanĝi
เปลือย/เปล่า nuda
เป้าหมาย/จุดมุ่งหมาย celo
แปล/ถอดความ traduki
แปลก stranga

ผลิตภัณฑ์จากยางพารา kaŭĉuka
ผักผลไม้หลายชนิดรวมกัน salado
ผ้าขนแกะ lano
ผู้โดยสาร pasaĝero
แผนที่ mapo
พระ/เณร monaĥo
พริก pipro
พลังงาน energio
พายุไต้ฝุ่น tajfuno
พิธีการ/พิธีกรรม ceremonio
เพรียบพร้อม/สมบูรณ์แบบ perfekta
เพื่อนบ้าน najbaro
ภาษาแสลง ĵargono
ภาษี imposto
มหาวิทยาลัย universitato
มหาสมุทร oceano
มะเขือเทศ tomato
มะม่วง mango
มังสวิรัติ vegetara
มั่นคง sekura
มีนิสัย/ความเคยชิน kutimi
มีเหตุผล/ใช้ได้ valida
มีไข้ febro
แมลง insekto
ไม้ ligno
ยอมรับ/ตอบรับ akcepti
ยุค/การกําเนิด generacio
ยุง moskito
ร่ม ombrelo
รสเปรี้ยว acida
ระดับขั้น nivelo
รักษา kuraci
รัง/ที่อยู่ nesto
รับประกัน/การรับรอง garantii
ราคา prezo
ร้านจําหน่ายยา apoteko
รายการอาหาร menuo
ทําให้เบื่อ enui
รูปแบบ formo
เร่งด่วน urĝa
เรื่องตลก ŝerco
โรงจอดรถ garaĝo
ไร่/นา bieno
ลักขโมย ŝteli
ลักษณะ/แบบ stilo
ลิง simio
ลิฟท์ lifto
เลขศูนย์ nulo
เล็บ ungo
เลือก elekti
เลือด/โลหิต sango
วงกลม cirklo
วัฒนธรรม kulturo

วัด templo
วัด/ชั่ง mezuri
วารสาร/หนังสือพิมพ์ ĵurnalo
วิตามิน vitamino
วิชาชีพ profesio
ศาสนา religio
ศาสนาพุทธ budhismo
ศิลปะ arto
เศรษฐกิจ ekonomio
สถานการณ์ situacio
สถาบัน/หน่วยงาน akademio
สบู่ sapo
สมอง cerbo
สร้าง/ผูกเรื่อง konstrui
สวนสาธารณะ parko
ส่วนลด/ลดราคา rabato
สะดวกสบาย komforta
สะพาน ponto
สัญลักษณ์ signo
สัญญา promeso
สั่น tremi
สันโดษ/ส่วนตัว privata
สันติภาพ paco
สากล universala
สาธารณะ publika
สําลี/ผ้าฝ้าย kotono
สิ่งจําเป็น necesa
สึนามิ cunamo
เส้น linio
เส้นประสาท nervo
เสนอ/แนะนํา oferto
เสี่ยง risko
เสียงดัง/เสียงตะโกน bruo
หนังสัตว์ ledo
หนังสือเดินทาง pasporto
หลังคา tegmento
หมอ doktoro
หัวเข่า genuo
หัวหอม cepo
เหตุการณ์/กรณี evento
เหยื่อ viktimo
เหล็ก ŝtalo
ให้การศึกษา eduki
ให้อาหาร nutri
ให้คําแนะนํา rekomendi
องศา grado
ออกเสียง (การเลือกตั้ง) baloti
อัญมณี/เครื่องประดับ juvelo
อันตราย danĝera
อาการคัน juki
อารยธรรม civilizacio
อ้วน/ไขมัน dika
อิจฉา/หึงหวง ĵaluza
อุณหภูมิ temperaturo
อุตสาหกรรม industrio
อุบัติเหตุ akcidento
เอกลักษณ์ unika
`