[
"-a		 (fin)	 ตัวลงท้ายของคำคุณศัพท์ในภาษาเอสเปรันโต",
"abel-o	  ผึ้ง;  abelejo  รังผึ้ง, รวงผึ้ง",
"abomen-i	 (tr) รังเกียจ; abomena น่ารังเกียจ",
"abon-i	 (tr) สมัครสมาชิก (นิตยสาร, หนังสือพิมพ์); abonanto   สมาชิก (นิตยสาร, หนังสือพิมพ์)",
"absces-o	  ฝี",
"abund-a	 อุดมสมบูรณ์; abundo   ความอุดมสมบูรณ์",
"acid-a	 เปรี้ยว, (f) แสบ; acido   กรด",
"-aĉ-	 (suf) พยางค์เติมท้ายบ่งชี้ถึงคุณภาพว่าไม่ดี: domaĉo   บ้านที่พุพัง; ĉevalaĉo   ม้าพยศ; aĉa แย่, ห่วย",
"aĉet-i	 (tr) ซื้อ; elaĉeti ไถ่ตัว; subaĉeti ติดสินบน",
"-ad-	 (suf) พยางค์เติมท้ายเพื่อแสดงถึงความต่อเนื่อง: parolado   การบรรยาย; naĝado   การว่ายน้ำ",
"adiaŭ ลาก่อน",
"administr-i	 (tr) บริหาร, จัดการ",
"admir-i	 (tr) ชื่นชม; admiro   ความรู้สึกชื่นชม; admirinda น่าชื่นชม",
"admon-i	 (tr) ว่ากล่าว, ตักเตือน, พูดกระตุ้น",
"ador-i	 (tr) สรรเสริญ, สักการะ",
"adres-o	   ที่อยู่; adresi (tr) เขียนที่อยู่, ส่งไปตามที่อยู่; retadreso ที่อยู่อีเมล",
"aer-o	   อากาศ",
"afabl-a	 เป็นมิตร; afableco; ความเป็นมิตร;  malafabla ไม่เป็นมิตร",
"afekt-i	 (tr) แกล้งทำ, เสแสร้ง",
"afer-o	   เรื่องราว, ข้าวของ",
"afiŝ-o	   โปสเตอร์, (เฟซบุ๊ก) โพสต์",
"afrank-i	 (tr) ชำระแสตมป์หรือการขนส่งล่วงหน้า",
"Afrik-o	   ทวีปแอฟริกา; afrikano   ชาวแอฟริกา",
"agi (tr) กระทำ, ปฏิบัติ; ago   การกระทำ; reago   ปฏิกิริยาโต้ตอบ",
"agl-o	   นกอินทรี",
"agord-o	   การตั้งเสียง, การตั้งค่า",
"agrabl-a	 เป็นที่พอใจ, น่าพึงพอใจ, ยินดี; malagrabla ไม่เป็นที่พอใจ, ไม่น่าพึงพอใจ, ไม่ยินดี",
"aĝ-o	  อายุ; aĝa มีอายุ; jaraĝa ขวบ, ปี: <i>Mi estas 9-jaraĝa</i>  ผมมีอายุ 9 ขวบ",
"ajl-o	 กระเทียม",
"ajn 	...ก็ได้ (ใช้คู่กับคำตารางกลุ่ม ki หรือกลุ่ม i) <i>kiu ajn</i> ใครก็ได้; <i>iam ajn</i> เมื่อไรก็ได้",
"-aĵ-	 (suf) พยางค์เติมท้ายซึ่งแสดงว่าเป็นสิ่งของ: novaĵo สิ่งที่ใหม่, ข่าว; porkaĵo เนื้อหมู; aĵo สิ่งของ",
"akcel-i	 (tr) เร่ง",
"akcept-i	 (tr) ยอมรับ, รับ; akceptejo ที่รับรอง; malakcepti ไม่ยอมรับ",
"akcident-o	 อุบัติเหตุ",
"akir-i	 (tr) ได้รับ, ได้...มาเป็นของตัวเอง > gajni, ricevi",
"akn-o	 สิว",
"akompan-i	 (tr) พาไป",
"akr-a	  คม, มีความคม; malakra ทื่อ",
"aktor-o	 นักแสดง; aktorino นักแสดงหญิง",
"aktual-a	 เกิดขึ้นในปัจจุบัน, เป็นปัจจุบัน, ใหม่",
"akurat-a	 ซึ่งตรงต่อเวลา, ซึ่งตามเวลาที่กำหนด",
"akuŝ-i	 (tr) คลอด",
"akuz-i	 (tr) กล่าวหา, กล่าวโทษ, ตั้งข้อหา",
"akv-o	 น้ำ; akvi (tr) รดน้ำ; superakvi น้ำท่วม  = inundi; sodakvo โซดา",
"al 	 (prep)	 ถึง; aliĝi (ntr) ต่อกัน, เข้าร่วม; aliĝilo ใบสมัคร",
"ali-a	 อื่น, อื่น ๆ; alie อย่างอื่น; aliulo คนอื่น",
"alkohol-o	 เเอลกอฮอล์; alkoholaĵo สุรา, เหล้า",
"almenaŭ 	 (adv)	 อย่างน้อย",
"almoz-o	 ของบริจาค (เงินหรืออื่น ๆ); almozanto คนขอทาน",
"alt-a	 สูง; alteco ความสูง; malalta เตี้ย",
"alud-i	 (x) บอกใบ้, บอกเป็นนัย",
"alumet-o	 ไม้ขีดไฟ",
"am-i	 (tr) รัก amo; ความรัก aminda น่ารัก; amindumi จีบ = flirti; enamiĝi ตกหลุมรัก; malami เกลียด",
"amar-a	 ขม",
"amas-o		ฝูงชน, กลุ่มของสิ่งที่มาก ๆ",
"ambaŭ	 (adj) 	 (pro)	 ทั้งสอง, ทั้งคู่",
"Amerik-o	 ทวีปอเมริกา > Usono ประเทศอเมริกา; amerikano ชาวทวีปอเมริกา ",
"amik-o	 เพื่อน; malamiko ศัตรู",
"amor-o	 ความต้องการทางเพศ, ความใคร่; amor-i	 (tr) (kun) มีเพศสัมพันธ์; amoristino โสเภณี",
"ampleks-o	 ขอบเขต, ความยิ่งใหญ่",
"amuz-i	 (tr) ทำให้...สนุก; amuziĝi สนุก",
"-an-	 (suf) พยางค์เติมท้ายหมายถึงสมาชิก: familiano สมาชิกในครอบครัว; klubano สมาชิกชมรม",
"anekdot-o	 เรื่องเล่าสั้น ๆ",
"angil-o	 ปลาไหล",
"angl-a	 อังกฤษ;  anglo ชาวอังกฤษ; Anglio ประเทศอังกฤษ",
"angul-o	 มุม",
"anĝel-o	 เทวดา; anĝelino นางฟ้า",
"anim-o	 จิตใจ",
"animal-o	 สัตว์ > besto สัตว์ (ยกเว้นคน)",
"ankaŭ 	 (adv)	 ดั้งนั้น, ด้วย",
"ankoraŭ 	 (adv)	 ยังคง",
"ankr-o	 สมอเรือ",
"anonc-i	 (tr) แจ้ง, ประกาศ; anonco ประกาศ",
"anser-o	 ห่าน",
"anstataŭ 	 (prep)	 แทน; anstaŭigi (per) แทนที่...(ด้วย)",
"-ant-	 (suf) พยางค์เติมท้ายแสดงลักษณะของกริยาที่กำลังดำเนินอยู่: lernanto ผู้ที่กำลังเรียน, นักเรียน; lernanta ซึ่งกำลังเรียน; lernante ในตอนที่กำลังเรียน; komencanto ผู้ที่กำลังเริ่มอะไรบางอย่าง, ผู้เริ่มต้น",
"antaŭ 	 (prep)	 ข้างหน้า",
"antikv-a	 โบราณ",
"apart-a	 เป็นส่วน ๆ; apartigi แยก...ออกเป็นส่วน ๆ",
"aparten-i	 (al) (ntr) เป็นของ",
"apenaŭ 	แทบจะไม่",
"aper-i	 (ntr) ปรากฏ",
"apetit-o	 ความเจริญอาหาร: Bonan apetiton! จะกินแล้วนะครับ",
"aplaŭd-i	 (tr) ปรบมือ",
"aplik-i	 (tr) ประยุกต์; นำไปใช้",
"apog-i	 (tr) ค้ำยัน, สนับสนุน",
"April-o	 เดือนเมษายน",
"aprob-i	 (tr) อนุมัติ; aprobo การอนุมัติ",
"apud 	 (prep)	 ข้าง ๆ, ถัดจาก, ถัดไป",
"-a	r- (suf) พยางค์ท้ายเพื่อแสดงความเป็นกลุ่ม ของสิ่งที่เหมือน ๆ กัน: vortaro พจนานุกรม; homaro มนุษยชาติ",
"arb-o	 ต้นไม้; arbaro ป่า",
"arbitr-a	 ตามอำเภอใจ",
"ard-i	 (ntr) เร่าร้อน, ร้อนแรง",
"arĝent-o	 เงิน (โลหะ) ",
"ark-o	 ส่วนโค้ง; pafarko ธนู",
"art-o	 ศิลปะ; artisto ศิลปิน",
"-a	s	 (fin)	 ตัวลงท้ายกริยาในปัจจุบันกาลหรือเกิดขึ้นเป็นปกติ (กำลัง...)",
"asekur-i	 (tr) ทำประกัน",
"asert-i	 (tr) ยืนยัน > insisti ยืนยัน, ยืนกราน;  aserto ข้อยืนยัน, ข้อพิสูจน์",
"aspekt-i	 (ntr) ดูเหมือน, ดูเหมือนว่า, ราวกับ > ŝajni",
"-at-	 (suf) พยางค์เติมท้ายแสดงลักษณะของกริยาถูกกระทำที่กำลังดำเนินอยู่; batato ผู้ที่ถูกตี; batata ซึ่งกำลังถูกตี; batate ในตอนที่กำลังถูกตี",
"atak-i	 (tr) โจมตี; บุก; ทำร้าย",
"atend-i	 (tr) รอคอย",
"atent-i	 (tr) ระวัง, เอาใจใส่; atentigi เตือน",
"atest-i	  (tr) ยืนยัน, เป็นพยาน; atestilo หลักฐาน, ใบประกาศนียบัตร",
"ating-i	 (tr) บรรลุถึง, ถึง (สถานที่)",
"aŭ 	 (kon)	 หรือ",
"aŭd-i	 (tr) ได้ยิน; aŭdo การได้ยิน; aŭdilo ลำโพง, หูฟัง = aŭskultilo; disaŭdigi กระจายเสียง",
"Aŭgust-o	 เดือนสิงหาคม",
"aŭskult-i	 (tr) ฟัง aŭskultanto ผู้ฟัง aŭskultilo = aŭdilo",
"aŭt-o	 รถยนต์ = aŭtomobilo",
"aŭtobus-o	 รถประจำทาง = buso",
"aŭtor-o	 นักประพันธ์, ผู้เขียน > verkisto ",
"aŭtun-o	 ฤดูใบไม้ร่วง",
"av-o	 ปู่, ตา; avino ยาย, ย่า",
"avar-a	 ขี้เหนียว",
"avert-i	 (tr) เตือน, ตักเตือน",
"avid-a	 โลภ, อยากมาก",
"azen-o	 ลา (สัตว์)",
"Azi-o	 ทวีปเอเชีย; aziano ชาวเอเชีย; Sud-o	rienta Azio เอเชียตะวันออกเฉียงใต้; Orienta Azio เอเชียตะวันออก",
"B",
"babil-i	 (x) คุยกันสนุก ๆ; babilema ช่างคุย",
"baht-o	, bat-o	 เงินบาท",
"bak-i	 (tr) อบ",
"bala-i	 (tr) กวาด; balailo ไม้กวาด",
"balanc-i	 (tr) แกว่ง > ekvilibro ความสมดุล",
"balbut-i	 (tr) พูด...อย่างตะกุกตะกัก; (ntr) พูดตะกุกตะกัก, พูดติดอ่าง",
"baldaŭ 	 (adv)	 ในไม่ช้า, เร็ว ๆ นี้",
"balen-o	 วาฬ",
"balot-i	 (ntr) ออกเสียง, ลงคะแนน; balotilo ใบลงคะแนน",
"ban-i	 (tr) อาบน้ำให้, เอา...แช่น้ำ <i>bani sin</i> อาบน้ำ; banejo อ่างอาบน้ำ",
"banan-o	 กล้วย; bananujo ต้นกล้วย",
"band-o	 วงดนตรี",
"Bangkok-o	 (PIV), Bankok-o	 กรุงเทพ; bangkokano คนกรุงเทพ",
"bank-o	 ธนาคาร",
"bapt-i	 (tr) บัพติสมา",
"bar-i	  (tr) ปิดทาง, ขัดขวาง; barilo สิ่งกีดขวาง",
"barakt-i	 (ntr) ตะเกียกตะกาย",
"barb-o	 เครา ",
"barel-o	 ถังบาเรล, (หน่วยตวง) บาเรล",
"baston-o	 ท่อนไม้; manĝbastonento ตะเกียบ; memorbastoneto = USB poŝmemorilo",
"bat-i	 (tr) ตี, เคาะจังหวะ",
"batal-i	 (ntr) ต่อสู้, รบ; batalo การต้อสู้",
"beb-o	 เด็กทารก",
"bed-o	 แปลง (ปลูกผัก)",
"bedaŭr-i	 (tr) เสียใจ, เสียดาย; bedaŭrinde ด้วยความเสียใจ",
"bel-a	 สวย, งาม, หล่อ; beleco ความสวย; belulino คนสวย",
"ben-i	 (tr) อวยพร; beno พร",
"benk-o	 ม้านั่งยาว",
"best-o	 สัตว์ (ยกเว้นคน) > animalo",
"bezon-i	 (tr) จำเป็น, ต้องการ; bezono ความจำเป็น, ความต้องการ",
"bicikl-o	 จักรยาน",
"bien-o	 ที่ดิน, ไร่, นา",
"bier-o	 เบียร์",
"bilard-o	 กีฬาบิลเลียด",
"bild-o	 รูปภาพ",
"bilet-o	 ตั๋ว; flugbileto ตั๋วเครื่องบิน",
"bird-o	 นก",
"blank-a	 สีขาว; blankulo คนผิวขาว; ฝรั่ง",
"blasfem-i	 (tr) ดูหมิ่น, ลบหลู่",
"blek-i	 (ntr) ร้อง (สัตว์)",
"blind-a	 ตาบอด; blindulo คนตาบอด",
"blond-a	 สีบรอนซ์",
"blov-i	 (tr) เป่า",
"blu-a	 สีฟ้า",
"bluz-o	 เสื้อสตรีแค่เอวหลวม ๆ",
"bo- 	 (pre)	 พยางค์เติมหน้าเพื่อแสดงถึงความสัมพันธ์อันเกิดจากการแต่งงาน: bopatro พ่อตา; bopatrino แม่ยาย",
"boat-o	 เรือ (ขนาดเล็ก) > ŝipo",
"boj-i	 (ntr) เห่า",
"bol-i	 (tr) เดือด; boligi ต้ม",
"bombon-o	 ลูกอม",
"bon-a	 ดี; bono สิ่งที่ดี; boneco ความดี; malbona ไม่ดี, เลว, ชั่ว",
"bord-o	 ตลิ่ง, ชายฝั่ง; marbordo ชายฝั่งทะเล",
"bot-o	 รองเท้าบูท",
"botel-o	 ขวด",
"bov-o	 วัวตัวผู้ = virbovo; bovino วัวตัวเมีย",
"brak-o	 แขน; brakumi กอด",
"branĉ-o	 กิ่งไม้, สาขา",
"brasik-o	 ผักกะหล่ำ",
"brav-a	 กล้าหาญ > kuraĝa",
"bret-o	 หิ้ง, ชั้น; librobreto ชั้นวางหนังสือ",
"bril-i	 (ntr) ส่องแสง",
"bros-o	 แปรง; brosi (tr) แปรง; dentbroso, dentobroso แปรงสีฟัน",
"brov-o	 คิ้ว",
"bru-i	 (ntr) ส่งเสียงรบกวน; bruo เสียงรบกวน",
"brul-i	 (ntr) ไฟไหม้, ถูกเผาด้วยไฟ; bruligi เผา",
"brun-a	 สีน้ำตาล",
"brust-o	 หน้าอก",
"brut-o	 สัตว์จตุบาท (เช่น วัว ม้า หมู แกะ)",
"bub-o	 เด็กซน",
"buĉ-i	 (tr) ฆ่า (สัตว์)",
"bufed-o	 อาหารบุฟเฟ่ต์",
"bulk-o	 ขนมปังก้อนเล็ก ๆ",
"bus-o	 = aŭtobuso รถบัส, รถเมล์",
"buŝ-o	 ปาก",
"buter-o	 เนยอ่อน > fromaĝo",
"butik-o	 ร้านขายของฉ่ำ; butikumi ซื้อของ",
"buton-o	 กระดุม, ปุ่ม",
"C",
"ced-i	 (x) ไม่ขัดขวาง, ไม่ต่อต้าน, สละสิทธิ์",
"cel-o	 เป้าหมาย",
"cent 	หนึ่งร้อย; centoj จำนวนเป็นร้อย ๆ",
"centr-o	 ภาคกลาง, ศูนย์กลาง; urbocentro ศาลากลาง",
"cerb-o	 สมอง",
"cert-a	 แน่นอน",
"cerv-o	 กวาง",
"ceter-a	 อื่น ๆ ที่เหลือ",
"ci คุณ (สรรพนามบุรุษที่สองเอกพจน์) (ไม่นิยมใช้) > vi",
"cifer-o	 อักษรตัวเลข > numero",
"cigared-o	 ซิการ์",
"cindr-o	 ขี้เถ้า",
"cirkonstanc-o	 สิ่งแวดล้อม",
"cirkuler-o	 หนังสือเวียน",
"cit-i	 ยก...มากล่าวถึง, อ้างถึง > mencii; citilo เครื่องหมายคำพูด “  ”",
"citron-o	 มะนาว",
"col-o	 นิ้ว (มาตราวัด) > futo",
"Ĉ",
"ĉagren-i	 (tr) ทำให้...รู้สึกไม่ดี, ทำให้...เสียใจ",
"ĉambr-o	 ห้อง; klasĉambro ห้องเรียน",
"ĉap-o	 หมวกแก๊ป",
"ĉapel-o	 หมวก",
"ĉapitr-o	 บท (ในหนังสือ) ",
"ĉar 	 (kon)	 เพราะว่า",
"ĉarm-a	 น่ารัก, มีเสน่ห์",
"ĉarpent-i	 (tr) ก่อสร้าง",
"ĉas-i	 (tr) ไล่ล่า (สัตว์); ĉasisto นักล่าสัตว์",
"ĉast-a	 บริสุทธ์, พรมจรรย์",
"ĉe 	 (prep)	 ที่",
"ĉef-a	 หลัก, สำคัญ; ĉefo ผู้นำ, หัวหน้า",
"ĉel-o	 เซลล์",
"ĉemiz-o	 เสื้อเชิ้ต",
"ĉen-o	 โซ่",
"ĉeriz-o	 ผลเชอร์รี่",
"ĉerp-i	 (tr) ตัก, เท (น้ำ); elĉerpi (tr) ตัก...จาก, เท...จาก, (f) ตัก/เท...จนหมด, เอา...ไปจนหมด; elcerpiĝo หมดพลัง, หมดไฟ",
"ĉes-i	 (ntr) เลิก, หยุด > halti",
"ĉeval-o	 ม้า",
"ĉi พยางค์บ่งชี้ถึงความใกล้เคียงผู้พูดใช้คู่กับคำตารางกลุ่ม t โดยจะอยู่ข้างหน้าหรือข้างหลังก็ได้: tio นั้น, tio ĉi นี่, tie ที่นั้น, tie ĉi ที่นี่; ใช้คู่กับคำนามหรือคำกริยาวิเศษณ์โดยจะวางข้างหน้าและจะต้องมีเครื่องหมายขีดคั่น: ĉi monato (= ĉi tiu monato) เดือนนี้, ĉi-nokte (ใน)คืนนี้",
"ĉia (adj) ทุกชนิด",
"ĉial 	 (adv)	 ทุก ๆ เหตุผล",
"ĉiam 	 (adv)	 ทุก ๆ เวลา, เสมอ",
"ĉie 	 (adv)	 ทุกแห่ง,  ทุกที่",
"ĉiel 	 (adv)	 ทุกวิธี",
"ĉiel-o	 ท้องฟ้า",
"ĉies 	 (pro)	 ของทุกคน, ทุก ๆ ... เป็นของ",
"ĉio 	 (pro)	 ทุกสิ่ง, ทุกอย่าง",
"ĉiom 	 (adv)	 ทุกจำนวน, ทั้งหมด",
"ĉirkaŭ 	 (prep)	 รอบ ๆ, ใกล้ ๆ",
"ĉiu 	 (pro)	 แต่ละคน, แต่ละสิ่ง; ĉiuj 	 (pro)	 ทุกคน, ทุก ๆ คน, ทุกสิ่ง, ทุก ๆ สิ่ง; ĉiu ... (adj) แต่ละ ...  ĉiuj ... ทุก ๆ ...",
"-ĉj- 	(suf) พยางค์เติมท้ายแสดงรูปแบบของชื่อเล่นเพศชาย: Patro = Paĉjo, Petro = Peĉjo",
"ĉokolad-o	 ช็อกโกแลต",
"ĉu ไหม, ใช่หรือไม่, หรือเปล่า; ĉu ... ĉu ... ไม่ว่าจะ...หรือ...",
"D",
"da 	 (prep)	 ของ (ใช้กับจำนวนหรือปริมาณ ซึ่งคำที่แสดงจำนวนจะอยู่อยู่ข้างหน้า) <i>ĉi tie troviĝas multe da homoj</i> ที่นี่มีคนมาก, <i>glaso da akvo</i> น้ำหนึ่งแก้ว",
"damaĝ-i	 (tr) ส่งผลกระทบ, ทำให้เสียหาย",
"danc-i	 (ntr) เต้นรำ; dancisto นักเต้น",
"danĝer-o	 อันตราย",
"dank-i	 (x) ขอบคุณ; dankon ขอบคุณ",
"dat-o	 วันที่, วันเดือนปี; dati (tr) ลงวันที่; ĝisdatigita ทำให้เป็นปัจจุบัน, อัปเดท",
"daŭr-i	 (ntr) ต่อเนื่อง; daŭrigi ทำต่อ, ต่อ",
"de 	 (prep)	 ของ, จาก, แห่ง",
"dec-a	 เหมาะสม, ถูกต้อง > taŭga",
"Decembr-o	 เดือนธันวาคม",
"decid-i	 (tr) ตัดสินใจ; decido การตัดสินใจ",
"deĉifr-i	 (tr) ถอดรหัส",
"dediĉ-i	 (tr) อุทิศ, ทุ่มเท; sindediĉo การอุทิศตัวเอง",
"defend-i	 (tr) ป้องกัน, ปกป้อง",
"degel-i	 (ntr) ละลาย (น้ำแข็ง)",
"deĵor-i	 (ntr) ปฏิบัติหน้าที่ตามเวลาที่กำหนด",
"dek 	สิบ; deka ลำดับที่สิบ",
"deklar-i	 (tr) กล่าว, ประกาศ; deklaro คำประกาศ",
"dekstr-a	 ขวา; maldekstra ซ้าย",
"demand-i	 (tr) ถาม; demando คำถาม; demandanto คนถาม",
"dens-a	 หนา, แน่น",
"dent-o	 ฟัน; dentego งา; dentisto ทันตแพทย์",
"depend-i	 (de) ขึ้นอยู่กับ > pendi",
"des ยิ่ง... (มักใช้คู่กับ ju) > ju",
"desegn-i	 (tr) วาด; desegnaĵo รูปวาด",
"destin-o	 โชคชะตา, จุดหมาย; destini (tr) กำหนดโชคชะตา, ตั้งใจจะมอบ, จัดไว้เพื่อ",
"detal-a	 ละเอียด; detalo รายละเอียด; detalema จู้จี้ ",
"detru-i	 (tr) ทำลาย",
"dev-i	 (tr) ต้อง; devo หน้าที่; devigi บังคับ",
"dezert-o	 ทะเลทราย",
"dezir-i	 (tr) ปรารถนา; deziro ความปรารถนา",
"di-o	 พระเจ้า",
"diabl-o	 ปีศาจ",
"diamant-o	 เพชร",
"difekt-i	 (tr) ทำให้...เสียหาย",
"diferenc-i	 (ntr) แตกต่าง = malsama",
"difin-i	 (tr) จำกัดความ, ให้ความหมาย",
"dign-o	 ศักดิ์ศรี, เกียรติ ",
"dik-a	 อ้วน; dikulo คนอ้วน",
"diligent-a	 ขยัน",
"dimanĉ-o	 วันอาทิตย์",
"dir-i	 (tr) บอก, พูด",
"direkt-o	 ทิศทาง",
"direktor-o	 ผู้อำนวยการ",
"dis- 	 (pre)	 พยางค์เติมหน้าเพื่อบ่งชี้ถึงการแยกจากกัน: dissendi ส่งกระจาย; disŝir-i	 ฉีกกระจาย",
"disk-o	 แผ่นดิสก์; kompaktdisko ซีดี",
"dispon-i	 (x) สามารถใช้ได้",
"disput-i	 (tr) โต้เถียง",
"disting-i	 (tr) แยกความแตกต่างของ",
"distr-i	 (tr)  รบกวน, ทำให้...รู้สึกเพลิดเพลิน, ทำให้...บันเทิงใจ",
"diven-i	 (tr) เดา",
"divers-a	(j) ต่าง ๆ",
"divid-i	 (tr) แยกส่วน, หาร",
"do 	 (kon)	 อย่างไรก็ตาม, ดังนั้น, ซึ่งนั้นก็คือ",
"doktor-o	 หมอ, แพทย์, ดอกเตอร์",
"dolĉ-a	 หวาน; dolĉaĵo ของหวาน",
"dolor-i	 (ntr) เจ็บปวด; doloro ความเจ็บปวด",
"dom-o	 บ้าน; stacidomo สถานีขนส่ง",
"domaĝ-o	 สิ่งที่น่าเสียใจ, สิ่งที่น่าเสียดาย",
"don-i	 (tr) ให้; disdoni แจก; eldoni จัดพิมพ์; eldonejo สำนักพิมพ์",
"donac-i	 (tr) ให้ของขวัญ; donaco ของขวัญ",
"dorm-i	 (ntr) นอนหลับ; dormema ง่วงนอน",
"dors-o	 หลัง",
"dot-o	 สินสอด",
"drink-i	 (ntr) ดื่มสุรา > trinki",
"drog-o	 ยา; drogaĉo ยาเสพติด",
"dron-i	 (ntr) จมน้ำตาย",
"du 	สอง; dua ที่สอง; duobla สองเท่า",
"dub-i	 (x) สงสัย > suspekti",
"dum 	 (kon)	 	 (prep)	 ในขณะที่, ระหว่าง",
"dung-i	 (tr) จ้าง",
"duŝ-i	 (tr) อาบน้ำ (โดยฟักบัว) > bani; duŝo การอาบน้ำ, (การแพทย์) การล้าง <i>intesta duŝo การล้างลำไส้</i>; duŝejo ห้องอาบน้ำ",
"E",
"-e		 (fin)	 ตัวลงท้ายกริยาวิเศษณ์",
"eben-a	 ราบ",
"-ebl-	 (suf) พยางค์เติมท้ายเพื่อแสดงถึงความเป็นไปได้; eble อาจเป็นได้, บางที; eblo ความเป็นไปได้; ebleco ลักษณะของความเป็นไปได้",
"ebri-a	 เมา; ebriulo คนเมา",
"-e	c- (suf) พยางค์เติมท้ายเพื่อระบุลักษณะ; beleco ความงาม; boneco ความดี; eco ลักษณะ",
"eĉ 	 (adv)	 แม้แต่, แม้กระทั่ง",
"eduk-i	 (tr) ให้การศึกษา, เลี้ยงดู; eduko, edukado การศึกษา; bonedukiteco การศึกษาดี, ความมีการศึกษา",
"edz-o	 สามี, ผัว; edzino ภรรยา, เมีย; geedziĝo การแต่งาน; geedziĝi แต่งงาน, กลายเป็นคู่สามีภรรยา",
"efektiv-a	 ที่จริง",
"efik-i	 (ntr) ส่งผล, ให้ผล; efiko ผล, ผลดี, ผลกระทบ",
"-eg-	 (suf) พยางค์เติมท้ายเพื่อแสดงขนาดใหญ่: bonege เยี่ยมมาก",
"egal-a	 เท่าเทียม",
"ego-o	 ความเห็นแก่ตัว; egoisto คนเห็นแก่ตัว",
"eĥ-o	 เสียงสะท้อน",
"-ej-	 (suf) พยางค์เติมท้ายเพื่อระบุว่าเป็นสถานที่: lernejo โรงเรียน; malsanulejo โรงพยาบาล",
"ek- 	 (pre)	 พยางค์เติมหน้าแสดงการเริ่มการกระทำ: eklerni เริ่มเรียน; ekparoli เริ่มพูด; ekscii เริ่มรู้",
"ekonomi-o	 เศรษฐกิจ ",
"eksces-a	 มากเกินไป",
"ekscit-i	 (tr) ทำให้ตื่นเต้น, ทำให้ตื่นตัว",
"ekskurs-o	 การเดินทาง, การท่องเที่ยว, ทัศนศึกษา > vojaĝo",
"ekspozici-o	 งานนิทรรศการ",
"ekster 	 (prep)	 ข้างนอก, ภายนอก ekstere ข้างนอก, ภายนอก",
"ekstr-a	 เพิ่มเติมพิเศษ",
"ekstrem-a	 ขีดสุด",
"ekvilibr-o	 ความสมดุลย์ > balanco",
"ekzamen-i	 (tr) สอบ; ekzameno การสอบ; ekzameniĝi (ntr) สอบ",
"ekzempl-o	 ตัวอย่าง > specimeno",
"ekzerc-i	 (tr) ฝึกหัด; ekzerco แบบฝึกหัด; ekzercaro หนังสือแบบฝึกหัด",
"ekzist-i	 (ntr) มีอยู่, มีชีวิตอยู่, มีขึ้น, ปรากฏ",
"el 	 (prep)	 ออกจาก, มาจาก; el- 	 (pre)	 แสดงถึงการออกมา: eliri ออกมา, แสดงการกระทำจนถึงที่สุด (บางคำเท่านั้น): ellerni เรียนจนถึงที่สุด, เรียนจนชำนาญ",
"elekt-i	 (tr) เลือก > selekti",
"elektr-o	 ไฟฟ้า > kurento; elektrejo โรงไฟฟ้า ",
"-em-	 (suf) พยางค์เติมท้ายเพื่อแสดงถึงแนวโน้มที่มีต่อสิ่งใดสิ่งหนึ่ง: laborema ขยัน; dormema ง่วงนอน ",
"embaras-o	 ความรู้สึกกังวลใจ, อาการคิดไม่ออก",
"emoci-o	 ความประทับใจ, ความซาบซึ้ง",
"en 	 (prep)	 ใน; en ...n เข้าไปข้างใน",
"enigm-o	 ปัญหาปริศนา",
"entrepren-i	 (tr) ดำเนินการ, จัดการ; entrepreno การประกอบการ, กิจการ; entreprenejo สถานประกอบการ; entreprenisto ผู้ประกอบการ",
"enu-i	 (ntr) รู้สึกเบื่อ; enuiga น่าเบื่อ > tedi",
"envi-i	 (x) อิจฉา > ĵaluza",
"-er-	 (suf) พยางค์เติมท้ายเพื่อแสดงการเป็นชิ้นเป็นอัน: mono เงิน, monero เหรียญ",
"erar-i	  (ntr) ผิด, ผิดผลาด; eraro สิ่งที่ผิด, ข้อผิดพลาด",
"escept-i	 (tr) ยกเว้น; escepto ข้อยกเว้น",
"esenc-o	 แก่น, เนื้อหาหลัก",
"eskap-i	 (tr)  (el) หนี (จาก), หลบหนี ",
"eskim-o	 ชาวเอสกิโม",
"esper-i	 (x) หวัง; espero ความหวัง; esperanto ผู้ที่มีความหวัง, ผู้ที่กำลังหวัง",
"Esperant-o	 ภาษาเอสเปรันโต; esperantisto ผู้ใช้ภาษาเอสเปรันโต; Esperantujo สถานที่ที่มีคนผู้ภาษาเอสเปรันโต; Esperantologio เอสเปรันโตศึกษา",
"esplor-i	 (tr) สำรวจ; esploristo นักสำรวจ, นักวิจัย",
"esprim-i	 (tr) แสดง, กล่าว",
"est-i	 (ntr) เป็น, อยู่, คือ; ĉeesti เข้าร่วม",
"estim-i	 (tr) เคารพ",
"esting-i	 (tr) ดับ (ไฟ)",
"-estr-	 (suf) พยางค์เติมท้ายเพื่อแสดงการเป็นหัวหน้า: urbo เมือง, urbestro เจ้าเมือง; estro ผู้นำ, หัวหน้า = ĉefo",
"-et-	 (suf) พยางค์เติมท้ายเพื่อแสดงขนาดที่เล็ก: hundo สุนัข, hundeto สุนัขตัวเล็ก",
"etaĝ-o	 ชั้นของอาคาร",
"etend-i	 (tr) ยื่น, ทำให้...ยาว",
"etern-a	 ตลอดไป, ชั่วนิรันดร์",
"Eŭrop-o	 ทวีปยุโรป; eŭropano ชาวยุโรป",
"eventual-a	 ที่เป็นไปได้, ที่เกิดขึ้นได้",
"evident-a	 ชัดเจน",
"evit-i	 (tr) หลีกเลี่ยง; evitinda ควรหลีกเลี่ยง",
"evolu-i	 (ntr) พัฒนา; evoluo การพัฒนา",
"F",
"fabel-o	 นิทาน",
"fabrik-o	 โรงงาน; fabriki (tr) ผลิต; fabrikanto เจ้าของโรงงาน",
"facil-a	 ง่าย; facileco ความง่าย",
"faden-o	 เส้นดาย",
"fajf-i	 (x) เป่านกหวีด, ผิวปาก; fajfilo นกหวีด",
"fajr-o	 ไฟ",
"fak-o	 แผนก, สาขาวิชา; fakulo ผู้เชี่ยวชาญ",
"faktor-o	 ข้อเท็จจริง, เอเย่นต์ขายของ, ปัจจัย",
"faktur-o	 ใบสั่งของ, ใบเสร็จ",
"fal-i	 (ntr) ตก; akvofalo น้ำตก",
"fald-i	 (tr) พับ",
"fals-a	 ปลอม",
"fam-o	 ชื่อเสียง; fama มีชื่อเสียง; famulo ผู้มีชื่อเสียง, คนดัง",
"famili-o	 ครอบครัว; familiano สมาชิกในครอบครัว",
"fand-i	 (tr) ทำให้...ละลาย",
"fanfaron-i	 (x) อวด, โอ้อวด",
"fantom-o	 ผี",
"far-i	 (tr) ทำ; fariĝi กลายเป็น = iĝi",
"farm-i	 (tr) ทำฟาร์ม; farmo ฟาร์ม",
"fart-i	 (ntr) สถานะของสุขภาพ <i>Kiel vi fartas? Mi fartas bone.</i> คุณเป็นอย่างไรบ้าง? ผมสบายดี; bonfarto การมีสุขภาพที่ดี",
"farun-o	 แป้งทำอาหาร",
"favor-a	 เอื้อเฟื้อ, เมตตา",
"Februar-o	 เดือนกุมภาพันธ์",
"feliĉ-a	 มีความสุข; feliĉo, feliĉeco ความสุข",
"fend-i	 (tr) ผ่า (ตามยาว); fendo รอยแตกตามยาว",
"fenestr-o	 หน้าต่าง",
"fer-o	 เหล็ก",
"feri-o	 วันหยุด",
"ferm-i	 (tr) ปิด > ŝalti; malfermi (tr) เปิด ",
"fervor-o	 ความกระตือรือร้น, ความมุ่งมั่น",
"fest-i	 (tr) ฉลอง; festo วันสำคัญทางศาสนา, เทศกาล",
"fianĉ-o	 คู่หมั้นชาย; finaĉino คู่หมั้นหญิง",
"fid-i	 (x) เชื่อใจ > kredi; fidinda น่าเชื่อถือ, น่าเชื่อใจ; memfido ความเชื่อมั่นตนเอง",
"fidel-a	 สื่อสัตย์, ซื่อตรง",
"fier-a	 ภูมิใจ",
"fiks-i	 (tr) ยึด, ตรึง, ทำให้...มั่งคง",
"fil-o	 ลูกชาย; filino ลูกสาว",
"fili-o	 สาขา",
"film-o	 ฟิล์ม, ภาพยนตร์; filmi (tr) ถ่าย(วิดีโอ); filmeto คลิป, หนังสั้น",
"fin-i	 (tr) จบ, เลิก >  ĉesi; finiĝi (ntr) จบ; fino ปลาย, ตอนจบ; finaĵo ตัวลงท้าย",
"fingr-o	 นิ้วมือ",
"firm-a	 มั่งคง",
"firma-o	บริษัท = kompanio",
"fiŝ-o	 ปลา; fiŝisto นักตกปลา, คนเลี้ยงปลา, คนขายปลา",
"flag-o	 ธง > standardo",
"flam-o	 เปลวไฟ",
"flank-o	 ข้าง, ด้าน",
"flar-i	 (tr) ดม",
"flat-i	 (x) ประจบ; flatema ขี้ประจบ",
"flav-a	 สีเหลือง",
"fleg-i	 (tr) รักษา, ดูแล (คนป่วย); flegistino พยาบาล",
"fleks-i	 (tr) งอ; fleksebla งอได้, ยืดหยุ่น",
"flirt-i	 (ntr) บินไปมา; จีบ = amidumi",
"flor-o	 ดอกไม้",
"flos-o	 แพ; flosi (ntr) ลอยน้ำ",
"flu-i	 (ntr) ไหล, ล่องลอย, ลื่นไหล, คล่อง",
"flug-i	 (ntr) บิน; flugilo ปีก",
"flustr-i	 (tr) กระซิบ",
"flut-o	 ขลุ่ย; flutisto นักเป่าขลุ่ย",
"foir-o	 งานแสดงสินค้า/บริการ",
"foj-o	 ครั้ง; foje ครั้งหนึ่ง, เคย; fojfoje บางครั้ง",
"foli-o	 ใบไม้",
"fond-i	 (tr) ก่อตั้ง, สร้าง; fondaĵo มูลนิธิ",
"font-o	 น้ำพุ, แหล่งข้อมูล",
"for 	 (adv)	 ไกล; for- 	 (pre)	 แสดงถึงความไกล, ไม่มีเหลือ forkuri วิ่งหนีไปไกล formanĝi กินจนไม่เหลือ",
"forges-i	 (x) ลืม; forgesema ขี้ลืม",
"forĝ-i	 (tr) หลอมโลหะ",
"fork-o	 ส้อม",
"form-o	 รูปแบบ",
"formik-o	 มด",
"forn-o	 เตาอบ",
"fort-a	 แข็งแรง; forto ความแข็งแรง, กำลัง; perforti (tr) ใช้กำลัง, ใช้ความรุนแรง",
"fortik-a	 แข็งแกร่ง",
"fos-i	 (tr) ขุด; fosilo เครื่องมือสำหรับขุด",
"fotel-o	 เก้าอี้มีที่วางแขน",
"frag-o	 ลูกสตรอเบอร์รี่",
"frakas-i	 (tr) ทำให้...แตก",
"frand-i	 (tr) กิน...อย่างเอร็ดอร่อย",
"frap-i	 (tr) ตี, เคาะ",
"frat-o	 พี่ชาย/น้องชาย; fratino พี่สาว/น้องสาว",
"fraŭl-o	 ชายโสด; fraŭlino นางสาว ",
"fraz-o	 ประโยค",
"fremd-a	 แปลกตา, ต่างประเทศ; fremdulo คนแปลกหน้า, ชาวต่างประเทศ",
"frenez-a	 บ้า, เพี้ยน; frenezulo คนบ้า",
"freŝ-a	 สด, ใหม่",
"fripon-o	 โจร, อันธพาล",
"friz-i	 (tr) ทำผม; frizist(in)o ช่างทำผม",
"fromaĝ-o	 เนยแข็ง > butero",
"frot-i	 (tr) ถู",
"fru-a	 แต่แรก, แต่เช้า, เร็ว",
"frukt-o	 ผลไม้",
"frunt-o	 หน้าผาก",
"fulm-o	 ฟ้าแลบ; fulmi ฟ้าแลบ; fulmobati, fulmofrapi ฟ้าผ่า",
"fum-o	 ควัน; fumi (ntr) สูบบุหรี่",
"fund-o	 ก้นบึ้ง",
"funebr-o	 การไว้ทุกข์",
"fung-o	 เห็ด",
"funt-o	 ปอนด์ (มาตราวัด)",
"furioz-a	 โกรธจัด, โกรธเป็นไฟ",
"fuŝ-i	 (tr) ทำ...ผิด, ทำ...ผิดพลาด, ทำ...เสีย",
"fut-o	 ฟุต (มาตราวัด) > colo",
"G",
"gaj-a	 ร่าเริง, เบิกบานใจ",
"gajn-i	 (tr) ได้รับ (จากความพยายามหรือจากการเสี่ยงโชค) > akiri, ricevi ",
"gant-o	 ถุงมือ",
"gard-i	 (tr) คุ้มครอง; ป้องกัน; gardisto คนคุ้มครอง",
"gast-o	 แขก; gastigi รับเป็นแขก; gastejo โรงแรมขนาดเล็ก; เกสต์เฮาส์",
"gastronomi-o	 ศิลปะการชิม, ศิลปะการทำอาหาร",
"gazet-o	 นิตยสาร > revuo",
"ge- 	 (pre)	 พยางค์เติมหน้าเพื่อแสดงถึงทั้งสองเพศ: geamikoj เพื่อนชายหญิง",
"gent-o	 ชนชาติ, เชื้อชาติ",
"genu-o	 หัวเข่า",
"geografi-o	 ภูมิศาสตร์",
"glaci-o	 น้ำแข็ง; glaciaĵo ไอศกรีม",
"glas-o	 แก้ว, ถ้วยแก้ว",
"glat-a	 เรียบ",
"glav-o	 มีดดาบ; glavingo ฝักมีดดาบ",
"glit-i	 (ntr) ลื่น",
"glob-o	 โลก, ลูกโลก",
"glor-i	 (tr) สรรเสริญ, เชิดชู, สดุดี",
"glu-i	 (tr) ติดกาว; gluo, gluaĵo, gluilo กาว",
"glut-i	 (tr) กลืน",
"gol-o	 ประตูฟุตบอล",
"gorĝ-o	 ลำคอ",
"gramatik-o	 ไวยากรณ์",
"grand-a	 ใหญ่; grandeco ความใหญ่",
"gras-a	 เป็นมัน, อ้วน",
"gratul-i	 (tr) แสดงความยินดี: Gratulojn! ขอแสดงความยินดีด้วย",
"grav-a	 สำคัญ; gravulo บุคคลสำคัญ",
"graved-a	 ท้อง, ตั้งครรภ์; gravediĝi ตั้งท้อง, ตั้งครรภ์; gravedulino คนท้อง, หญิงตั้งครรภ์",
"gren-o	 ธัญพืช",
"grimp-i	 (sur) (ntr)  ปีน",
"griz-a	 สีเทา",
"grund-o	 ดิน",
"grup-o	 กลุ่ม",
"gust-o	 รสชาติ; gustumi (tr) ชิม",
"gvid-i	 (tr) นำทาง, นำเที่ยว, แนะนำ; gvidisto คนนำทาง, คนนำเที่ยว",
"Ĝ",
"ĝangal-o	 ป่าดงดิบ",
"ĝarden-o	 สวน",
"ĝem-i	 (ntr) คราง, ครวญ",
"ĝemel-o	 แฝด",
"ĝen-i	 (tr) รบกวน, ทำให้รำคาญ",
"ĝeneral-a	 ทั่ว ๆ ไป",
"ĝentil-a	 สุภาพ",
"ĝi มัน (สรรพนามบุรุษที่ 3 เอกพจน์ ไม่แสดงเพศ)",
"ĝis 	 (prep)	 จนกระทั่ง, ถึง",
"ĝoj-i	 (ntr) ยินดี, ดีใจ; ĝojo ความยินดี, ความดีใจ",
"ĝu-i	 (tr) สนุก, เพลิดเพลิน",
"ĝust-a	 ถูกต้อง; ĝustigi (tr) แก้ให้ถูก = korekti",
"H",
"ha! 	 (int)	 ฮะ!",
"hajl-o	 ลูกเห็บ",
"hak-i	 (tr) ผ่าด้วยขวาน; hakilo ขวาน",
"hal-o	 หอประชุมใหญ่ ",
"halo!, ha lo!, ha-lo! ฮัลโหล",
"halt-i	 (ntr) หยุด (การเคลื่อนไหว) > ĉesi; haltejto ป้ายหยุดรถ; busheltejo ป้ายหยุดรถประจำทาง",
"har-o	 เส้นขน; hararo ผม",
"haŭt-o	 ผิวหนัง",
"hav-i	 (tr) มี; enhavo สิ่งที่อยู่ข้างใน, สารบัญ",
"haven-o	 ท่าเรือขนาดใหญ่; flughaveno สนามบิน",
"hejm-o	 บ้าน",
"hejt-i	 ทำให้...ร้อน",
"hel-a	 สว่าง, กระจ่าง",
"help-i	 (tr) ช่วยเหลือ; helpo การช่วยเหลือ; helpanto ผู้ช่วย",
"herb-o	 หญ้า",
"hered-i	 (ntr) รับมรดก; heredaĵo มรดก",
"hezit-i	 (ntr) ลังเล",
"hieraŭ 	 (adv)	 เมื่อวาน; antaŭhieraŭ เมื่อวานซืน",
"himn-o	 เพลงสวด; เพลงสรรเสริญ",
"hirud-o	 ปลิง",
"hirund-o	 นกนางแอ่น",
"histori-o	 ประวัติศาสตร์",
"ho! 	 (int)	 โอ้, พุทโธ่",
"hodiaŭ 	 (adv)	 วันนี้",
"hom-o	 คน, มนุษย์; homaro มนุษยชาติ",
"honest-a	 ซื่อสัตย์, ใจจริง, ไม่หลอกลวง",
"honor-i	 (tr) ให้เกียรติ, ยกย่อง; honoro เกียรติ, เกียรติยศ ",
"hont-i	 (x) อาย, อับอาย",
"hor-o	 ชั่วโมง; horaro ตารางเวลา",
"horizont-o	 เส้นขอบฟ้า, แนวนอน",
"horloĝ-o	 นาฬิกา; brakhorloĝo นาฬิกาข้อมือ",
"hospital-o	 โรงพยาบาล = malsanulejo",
"hotel-o	 โรงแรม",
"humil-a	 ถ่อมตัว, เจียมตัว, อ่อนน้อม = modesta; humileco  การถ่อมตัว, การเจียมตัว, การอ่อนน้อม",
"humor-o	 อารมณ์",
"humur-o	 อารมณ์ขัน",
"hund-o	 สุนัข, หมา",
"Ĥ",
"ĥameleon-o	 กิ้งก่าคามิเลียน",
"ĥaos-o	 = kaoso ความวุ่นวาย",
"ĥemi-o	 = kemio เคมี",
"ĥor-o	 = koruso การร้องประสานเสียง",
"I",
"-i		 (fin)	 ตัวลงท้ายของกริยาไม่แสดงกาล (ใช้ต่อจากกริยาที่ผันแล้ว <i>Mi povas paroli Esperanton</i> ผมสามารถพูดภาษาเอสเปรันโต, หรือใช้เป็นอาการนามขึ้นต้นประโยค <i>resti kun leono estas danĝere</i> การอาศัยอยู่กับสิงโตเป็นสิ่งที่อันตราย)",
"ia 	 (pro)	 ชนิดใดชนิดหนึ่ง",
"ial 	 (adv)	 บางเหตุผล",
"iam 	 (adv)	 บางเวลา, เคย",
"-id-	(suf) พยางค์เติมท้ายเพื่อแสดงว่าเป็นลูก; ido ลูก",
"ide-o	 แนวคิด, ไอเดีย",
"ideal-a	 อุดมคติ; idealisto นักอุดมคติ",
"ideologi-o	 แนวคิดอุดมคติ = idearo",
"ie 	 (adv)	 ที่ใดที่หนึ่ง, สักที่หนึ่ง",
"iel 	 (adv)	 บางวิธี",
"ies 	 (pro)	 ...ของใครบางคน",
"-ig-	 (suf) พยางค์เติมท้ายเพื่อบ่งชี้ความเป็นสกรรมมักใช้กับกริยา: manĝigi ทำให้...กิน, ให้อาหาร; lacigi ทำให้...เหนื่อย",
"-iĝ-	 (suf) พยางค์เติมท้ายมีความหมายถึงการรับสถานะใหม่: sidi นั่งอยู่; sidiĝi รับสถานะของการนั่ง = นั่งลง; iĝi กลายเป็น = fariĝi",
"-il-	 (suf) พยางค์เติมท้ายเพื่อแสดงว่าเป็นอุปกรณ์หรือเครื่องมือ: skribilo เครื่องเขียน; muzikilo เครื่องดนตรี; ilo อุปกรณ์, เครื่องมือ",
"ili 	 (pro)	 พวกเขา, พวกมัน; ilia ของพวกเขา, ของพวกมัน",
"imag-i	 (tr) จินตนาการ; imago จินตนาการ",
"imit-i	 (tr) เลียนแบบ",
"impost-o	 ภาษี; impostisto คนเก็บภาษี",
"impres-o	 ความประทับใจ",
"impuls-o	 แรงกระตุ้น, แรงพลัก",
"-in-	 (suf) พยางค์เติมท้ายเพื่อแสดงว่าเป็นเพศหญิง: viro ผู้ชาย, virino ผู้หญิง",
"incit-i	 (tr) ยั่วโมโห",
"-ind-	 (suf) พยางค์เติมท้ายเพื่อแสดงว่าคุณค่าหรือมีความสมควร: aminda น่ารักใคร่; manĝinda น่ากิน",
"indian-o	 ชาวอินเดียนแดง",
"indign-i	 (ntr) แสดงอาการไม่พอใจ, โกรธแค้น",
"infan-o	 เด็กชาย",
"infekt-i	 (tr) ทำให้...ติดเชื้อ",
"infer-o	 นรก",
"influ-o	 อธิพล; influi (tr) มีอิธพลต่อ",
"inform-i	 (tr) ประชาสัมพันธ์; informo ข้อมูลประชาสัมพันธ์",
"-ing-	 (suf) พยางค์เติมท้ายเพื่อแสดงด้ามจับหรือปลอกสวม",
"iniciat-i	 (tr) ริเริ่ม; iniciatinto ผู้ริเริ่ม",
"ink-o	 หมึก",
"inklin-a	 มีแนวโน้ม",
"insekt-o	 แมลง",
"insign-o	 เครื่องหมาย, เครื่องหมายแสดงยศ",
"insist-i	 (ntr) ยืนยัน, ยืนกราน > aserti ยืนยัน",
"inspir-i	 (tr) ให้แรงบันดาลใจ; inspiro แรงบันดาลใจ",
"instig-i	 (tr) กระตุ้น, ส่งเสริม",
"instru-i	 (tr) สอน; instruisto ครู",
"insul-o	 เกาะ; insularo หมู่เกาะ",
"insult-i	 (tr) ดูถูก",
"-int-	 (suf) พยางค์เติมท้ายแสดงลักษณะของกริยาที่ดำเนินไปแล้ว",
"intenc-i	 (tr) ทำในระยะเวลาสั้น",
"intens-a	 ตั้งใจ; intenso ความตั้งใจ",
"inter 	 (prep)	 อยู่ในระหว่าง, ท่ามกลาง",
"interes-a	 น่าสนใจ; intereso ความสนใจ; interesi (tr) น่าสนใจสำหรับ <i>Ŝi tre interesas min เธอน่าสนใจมากสำหรับผม</i>",
"intern-a	 ด้านใน; ภายใน",
"interpret-i	 (tr) ตีความ, ล่าม; interpretisto ล่าม",
"invit-i	 (tr) เชิญ; invitilo จดหมายเชิญ",
"io 	 (pro)	 อะไรสักอย่างหนึ่ง, บางอย่าง <i>io interesa บางอย่างที่น่าสนใจ</i>",
"iom 	 (adv)	 จำนวนหนึ่ง, นิดหน่อย",
"ir-i	 ไป; eliri (ntr) ออกข้างนอก, ออกสู่สาธารณะ; elirejo ทางออก; eniri เข้ามาใน; foriri จากไปไกล",
"-is		 (fin)	 ตัวลงท้ายของกริยารูปอดีตกาล (...แล้ว)",
"-ist-	 (suf) พยางค์เติมท้ายเพื่อแสดงว่าเป็นผู้ประกอบอาชีพหรือผู้มีความเชื่อ: instruisto ครู; naciisto นักชาตินิยม",
"-it-	 (suf) พยางค์เติมท้ายแสดงลักษณะของกริยาถูกกระทำที่ดำเนินไปแล้ว",
"iu 	 (pro)	 คนใดคนหนึ่ง, สิ่งใดสิ่งหนึ่ง (adj) บาง...",
"J",
"-j		 (fin)	 ตัวลงท้ายแสดงความเป็นพหูพจน์",
"ja อย่างแท้จริง, แน่นนอน",
"jaĥt-o	 เรือยอร์ช",
"jak-o	 เสื้อแจ็คเก็ต",
"jam	 	 (adv)	 แล้ว",
"Januar-o	 เดือนมกราคม",
"japan-o	 ชาวญี่ปุ่น; japana ญี่ปุ่น; Japan-i	o ประเทศญี่ปุ่น",
"jar-o	 ปี; ĉiujare ทุกปี; novjaro วันขึ้นปีใหม่",
"je 	 (prep)	 ใน, ที่, ต่อ ",
"jen	 นี่, ดูสิ",
"jes	 ใช่; kapjesi พยักหน้าใช่",
"ju...des... 	 (adv)	 ยิ่ง... ยิ่ง....",
"juĝ-i	 (tr) ตัดสิน, พิพากษา; juĝejo ศาล; juĝisto ผู้พิพากษา",
"Juli-o	 เดือนกรกฎาคม",
"jun-a	 หนุ่ม, สาว; juneco ความหนุ่มสาว; junulo วัยรุ่น; maljuna แก่",
"jung-i	 (tr) ลาก",
"Juni-o	 เดือนมิถุนายน",
"jup-o	 กระโปรง",
"jur-o	 กฎหมาย > leĝo",
"just-a	 ยุติธรรม; justeco ความยุติธรรม",
"juvel-o	 เพชรพลอย",
"Ĵ",
"ĵaluz-a	 อิจฉา, หึง > envii",
"ĵaŭd-o	 วันพฤหัสบดี",
"ĵet-i	 (tr) ขว้าง, ปา",
"ĵur-i	 (tr) สาบาน",
"ĵurnal-o	 หนังสือพิมพ์; ĵurnaristo นักข่าว, นักหนังสือพิมพ์",
"ĵus 	 (adv)	 เพิ่งจะ",
"K",
"kadr-o	 กรอบ; kadre (de) ในกรอบ(ของ)",
"kaduk-a	 ชำรุด",
"kaf-o	 กาแฟ; kafejo ร้านกาแฟ",
"kaĝ-o	 กรง",
"kaj 	 (kon)	 และ",
"kajer-o	 สมุด",
"kaldron-o	 หม้อขนาดใหญ่",
"kalendar-o	 ปฏิทิน",
"kalkul-i	 (tr) คำนวณ, นับ",
"kalumni-i	 (tr) ใส่ร้าย",
"kamp-o	 ทุ่ง, นา, สนาม, พื้นที่; kamparo ท้องทุ่ง",
"kancer-o	 มะเร็ง; mamkancero มะเร็งเต้านม",
"kandel-o	 เทียน",
"kanjon-o	 หุบเขาลึก",
"kant-i	 (x) ร้องเพลง; kanto เพลง",
"kap-o	 ศีรษะ, หัว ",
"kapabl-a	 มีความสามารถ; kapablo ความสามารถ",
"kapr-o	 แพะ",
"kapric-o	 ความต้องการที่คาดเดาไม่ได้, การเอาแต่ใจ",
"kapt-i	 (tr) จับ",
"kar-a	 ที่รัก, มีคุณค่า, ราคาแพง = multekosta",
"karb-o	 ถ่านหิน",
"kares-i	 (tr) ลูบเบา ๆ ด้วยความรัก",
"karier-o	 อาชีพ, เส้นทางชีวิต",
"karot-o	 แครอท",
"kart-o	 การ์ด, บัตร bildkarto ไปรษณียบัตร",
"kas-o	 ที่เก็บเงิน; kasisto เจ้าหน้าที่การเงิน",
"kastel-o	 ปราสาท",
"kaŝ-i	 (tr) ซ่อน",
"kat-o	 แมว",
"kategori-o	 หมวดหมู่",
"katen-o	 ตรวน; mankateno กุญแจมือ",
"kaŭz-i	 (tr) เป็นเหตุที่ทำให้เกิด; kaŭzo เหตุที่ทำให้เกิด",
"kav-o	 โพรง",
"kavern-o	 ถ้ำ",
"ke 	 (kon)	 ว่า (ใช้เริ่มอนุปะโยค)",
"kel-o	 ห้องใต้ดิน",
"kelk-a	 จำนวนไม่มาก, บาง...: kelkaj homoj บางคน",
"kern-o	 แก่น",
"kest-o	 หีบ",
"kia (adj) ชนิดไหน, แบบไหน; 	 (int)	 ใช้แสดงการอุทานแสดงความประหลาดใจ โดยใช้ร่วมกับคำนามมาขยาย; (ril) ซึ่งเป็นอย่างที่",
"kial 	 (adv)	 ทำไม, เหตุใด",
"kiam 	 (adv)	 เมื่อไร, ตอนไหน; (ril) เมื่อ, ในตอนที่",
"kie 	 (adv)	 ที่ไหน (ril) ที่ซึ่ง, ในที่ซึ่ง",
"kiel 	 (adv)	 อย่างไร, วิธีไหน; 	 (int)	 ใช้แสดงการอุทานแสดงความประหลาดใจ โดยใช้ร่วมกับคำคุณศัพท์หรือกริยาวิเศษณ์มาขยาย; (ril) เหมือน, ดั่ง, ราวกับ",
"kies 	 (pro)	 ของใคร; (ril) ซึ่ง...ของ... <i>Jen estas mia amiko, kies nomo estas Marko</i> นี่คือเพื่อนของผม ซึ่งชื่อของเขาคือมาร์ก (นี่คือเพื่อนของผมที่ชื่อว่ามาร์ก)",
"kilogram-o	 กิโลกรัม",
"kilometr-o	 กิโลเมตร",
"kin-o	 ภาพยนตร์; kinejo โรงภาพยนตร์",
"kio						(adj) อะไร (ril) ซึ่ง",
"kiom 	 (adv)	 เท่าไหร่; 	 (int)	 ใช้แสดงการอุทานแสดงความประหลาดใจที่เกี่ยวข้องกับจำนวน",
"kis-i	 (tr) จูบ; kiso จุมพิต kisinda น่าจูบ",
"kiu 	 (pro)	 อันไหน,  คนไหน, ใคร; (adj) ...ไหน (ril); 	 (adv)	 ซึ่งเป็นผู้ที่, ซึ่งเป็นสิ่งที่; (adj) ซึ่งเป็น...ที่",
"klar-a	 กระจ่าง, สะอาด, ใส; klarigi ทำให้กระจ่าง, อธิบาย",
"klas-o	 ชั้นเรียน; samklasano เพื่อมร่วมชั้นเรียน",
"kler-a	 มีวัฒนธรรม, มีการศึกษา, มีความรู้, klerulo ผู้มีความรู้",
"klin-i	 (tr) ทำให้...โค้ง, ก้ม",
"kling-o	 ใบมีด",
"klopod-i	 (ntr) พยายาม",
"klub-o	 ชมรม; klubano สมาชิกชมรม",
"knab-o	 เด็กผู้ชาย; knabino เด็กหญิง",
"kned-i	 (tr) นวด; ปั้น",
"kok-o	 ไก่ตัวผู้; kokido ลูกเจี๊ยบ; kokino ไก่ตัวเมีย",
"kol-o	 คอ",
"kolbas-o	 ไส้กรอก",
"kolekt-i	 (tr) รวบรวม, สะสม",
"koler-i	 (x) โกรธ; kolero ความโกรธ",
"kolomb-o	 นกพิราบ",
"kolon-o	 เสา",
"kolor-o	 สี; kolorigi ระบายสี, ทาสี",
"kom-o	 เครื่องหมายลูกน้ำ (,)",
"komb-i	 (tr) หวี (ผม); kombilo หวี",
"komenc-i	(tr) เริ่ม (บางอย่าง); komenco การเริ่มต้น (บางอย่าง); komenciĝi (ntr) เริ่ม",
"komerc-i	 (tr) ทำการค้าขาย, ทำธุรกิจ;  komerco การทำการค้าขาย, การทำธุรกิจ; komercisto นักธุรกิจ ",
"komfort-a	 สบาย; komforto ความสบาย",
"kompar-i	 (tr) เปรียบเทียบ; komparo การเปรียบเทียบ",
"kompat-i	 (x) สงสาร, เห็นใจ; kompatinda น่าสงสาร",
"kompil-i	 (tr) เรียบเรียง, รวบรวม",
"komplet-a	 สมบูรณ์; kompletigi ทำให้...สมบูรณ์",
"komplez-o	 การเอาอกเอาใจ",
"komplik-i	 (tr) ทำให้ซับซ้อน; komplika ซับซ้อน",
"kompren-i	 (tr) เข้าใจ; kompreno ความเข้าใจ",
"komun-a	 ทั่วไป, เป็นที่ใช้ด้วยกัน; komunumo ชุมชน",
"komunik-i	 (tr) สื่อสาร",
"kon-i	 (tr) รู้จัก; konatiĝi ได้รู้จัก; diskonigi ทำให้...รู้, แชร์",
"koncern-i	 (tr) มีส่วนเกี่ยบกับ, มี",
"kondamn-i	 (tr) ลงความเห็นว่า...ต้องได้รับโทษ",
"kondiĉ-o	 เงื่อนไข",
"konduk-i	 (tr) พา, นำพา; enkonduki (tr)  แนะนำ",
"kondukt-i	 (tr) นำพา (ความร้อน, กระแสไฟฟ้า)",
"konfid-i	 (tr) ไว้วางใจ, เชื่อใจ",
"konfirm-i	 (tr) ยืนยัน, คอนเฟิร์ม",
"konform-a	 ตรงกับ, เข้ากันได้, สอดคล้อง",
"konfuz-i	 (tr) สับสน; konfuzo ความสับสน",
"kongres-o	 การประชุมใหญ่; kongresejo สถานที่จัดประชุมใหญ่",
"konjekt-i	 (tr) คาดเดา, อนุมาน",
"konklud-i	 (tr) ลงความเห็น, สรุป",
"konsci-i	 (tr) รับรู้, มีสติ, รู้ตัว",
"konscienc-o	 สติ, การมีสติ",
"konsent-i	 (x) เห็นด้วย",
"konsider-i	 (tr) พิจารณา",
"konsil-i	 (tr) แนะนำ, ให้คำแนะนำ; konsilo คำแนะนำ",
"konsist-i	 (el) (ntr) ประกอบ(จาก)",
"konsol-i	 (tr) ให้กำลังใจ",
"konstat-i	 (tr) ยืนยัน, สรุป,",
"konstern-i	 (tr) ทำให้...ไม่สบายใจ, ทำให้...เป็นกังวล",
"konstituci-o	 รัฐธรรมนูญ",
"konstru-i	  (tr) สร้าง, ก่อสร้าง; konstruaĵo สิ่งก่อสร้าง, อาคาร",
"konsum-i	 (tr) บริโภค",
"kontent-a	 พอใจ",
"kontrakt-i	 (tr) ทำสัญญา; kontrakto หนังสือสัญญา",
"kontraŭ 	 (prep)	 ตรงกันข้าม, ต่อต้าน, ในราคา",
"konven-i	 (tr) เหมาะสม, เข้ากัน",
"konvink-i	 (tr) โน้มน้าว",
"kor-o	 หัวใจ",
"korb-o	 ตะกร้า",
"korekt-i	 (tr) = ĝustigi",
"korespond-i	 (ntr) ติดต่อทางจดหมาย",
"korp-o	 ร่างกาย",	
"kort-o	 สนามหญ้าบริเวณหน้าบ้าน",
"korv-o	 นกกา",
"kost-i	 (ntr) มีราคา <i>Ĉi tiu vortareto kostas nur dudek bahtojn</i> พจนานุกรมเล่มนี้ราคายี่สิบบาทเท่านั้น; kosto ราคา; multekosta แพง",
"kotiz-o	 ค่าใช้จ่าย, ค่าลงทะเบียน",
"kovert-o	 ซองจดหมาย",
"kovr-i	 (tr) คลุม; malkovri (tr) พบเจอ (สิ่งที่ซ่อนอยู่)",
"kraĉ-i	 (tr) ถุย; kraĉaĵo น้ำลาย, เสมหะ",
"krajon-o	 ดินสอ",
"kramp-o	 ตัวหนีบ; เครื่องหมายวงเล็บ ()",
"kran-o	 หัวก๊อกน้ำ",
"kravat-o	 เนคไท",
"kre-i	 (tr) สร้าง, สรรค์สร้าง; kreinto ผู้สร้าง, ผู้ประดิษฐ์",
"kred-i	 (x) เชื่อ > fidi",
"krem-o	 ครีม",
"krepusk-o	 แสงตะวันยามรุ่งหรือยามลับขอบฟ้า",
"kresk-i	 (ntr) เจริญเติบโต; kreskigi ทำให้...เจริญเติบโต, ปลูก",
"kret-o	 ชอล์ก",
"krev-i	 (ntr) แตก (จากด้านใน)",
"kri-i	 (ntr) ตะโกน",
"krim-o	 อาชญากรรม",
"kripl-a	 พิการ",
"kritik-i	 (tr) วิพากษ์วิจารณ์",
"krom 	 (prep)	 นอกจาก",
"kruc-o	 เครื่องหมายกากบาท, เครื่องหมายรูปกางเขน",
"kruĉ-o	 เหยือกน้ำ",
"krud-a	 ดิบ",
"kruel-a	 โหดร้าย, โหดเหี้ยม",
"krur-o	 ขา",
"krut-a	 สูงชัน, แหลม",
"kudr-i	 (tr) เย็บ(ผ้า); kudrilo เข็มเย็บผ้า",
"kuir-i	 (tr) ทำอาหาร; kuirejo ครัว",
"kuk-o	 ขนมเค้ก; kuketo คุกกี้",
"kukum-o	 แตงกวา",
"kuler-o	 ช้อน",
"kulp-a	 มีความผิด",
"kun 	 (prep)	 กับ, ด้วย; kune ด้วยกัน",
"kunikl-o	 กระต่าย",
"kur-i	 (ntr) วิ่ง; forkuri วิ่งหนีไปไกล",
"kurac-i	 (tr) รักษา; kuracisto แพทย์",
"kuraĝ-a	 กล้า, กล้าหาญ > brava",
"kurb-a	 โค้ง",
"kurent-o	 กระแสไฟฟ้า > elektro",
"kurs-o	 หลักสูตรการเรียน",
"kurten-o	 ม่าน, ฉาก",
"kusen-o	 หมอน; kapkuseno หมอนหนุนหัว",
"kuŝ-i	 (ntr) นอน, วาง",
"kutim-o	 นิสัย; alkutimiĝi (ntr) ทำให้กลายเป็นนิสัย",
"kuz-o	 ลูกพี่ลูกน้อง",
"kvalit-o	 คุณสมบัติ, คุณลักษณะ",
"kvankam 	 (kon)	 ถึงแม้ว่า (มักใช้คู่กับ tamen) > malgraŭ",
"kvant-o	 จำนวน",
"kvar 	สี่; kvara ที่สี่",
"kvartal-o	 จัตุรัส (ในเมือง)",
"kvazaŭ 	 (kon)	 	 (adv)	 ราวกับ",
"kviet-a	 เงียบสงบ",
"kvin 	ห้า; kvina ที่ห้า",
"L",
"la	 คำนำหน้านามชี้เฉพาะ",
"labor-i	 (ntr) ทำงาน; laborema ขยันทำงาน; laborejo สถานที่ทำงาน; laboristo พนักงาน, คนงาน",
"lac-a	 เหนื่อย; laciga ซึ่งทำให้เหนื่อย",
"lacert-o	 กิ้งก่า",
"lag-o	 ทะเลสาบ",
"lakt-o	 นม",
"lamp-o	 โคมไฟ",
"lan-o	 ขนสัตว์",
"land-o	 ประเทศ; alilando, eksterlando ต่างประเทศ; alilandano ชาวต่างประเทศ = eksterlandano",
"lang-o	 ลิ้น",
"larĝ-a	 กว้าง",
"larm-o	 น้ำตา; larmi (ntr) น้ำตาไหล",
"las-i	 (tr) ปล่อย; ellasi (tr) ปล่อยออกมา; forlasi (tr) จาก, ไปจาก",
"last-a	 ครั้งสุดท้าย, ครั้งล่าสุด; antaŭlasta ก่อนสุดท้าย",
"laŭ 	 (prep)	 ตาม, ตามแต่, ที่กำหนดโดย",
"laŭd-i	 (tr) สรรเสริญ, ชื่นชม; laŭdinda น่าสรรเสริญ, น่าชื่นชม",
"laŭt-a	 ดัง (เสียง); laŭtigilo  ลำโพง",
"lav-i	 (tr) ล้าง ",
"lecion-o	 บทเรียน",
"led-o	 หนังสัตว์",
"leg-i	 (tr) อ่าน; legado การอ่าน; legolibro หนังสือฝึกหัดอ่าน",
"legom-o	 ผัก",
"leĝ-o	 กฎหมาย, ข้อบังคับ > juro",
"lek-i	 (tr) เลีย",
"lens-o	 เลนส์",
"leon-o	 สิงโต",
"lepor-o	 กระต่ายป่า",
"lern-i	 (tr) เรียน; lernanto นักเรียน; ellerni เรียนจนชำนาญ",
"lert-a	 ฉลาด, มีทักษะ > saĝa",
"leter-o	 จดหมาย",
"lev-i	 (tr) ยก (บางอย่าง); leviĝi ลุกขึ้น, ขึ้น",
"li 	 (pro)	 เขา (ผู้ชาย); lia ของเขา (ผู้ชาย)",
"liber-a	 อิสระ",
"libr-o	 หนังสือ; libreto หนังสือเล่มเล็ก",
"lift-o	 ลิฟต์",
"lig-i	 (tr) ผูก; ligo สหพันธ์; ligilo ลิงก์",
"lign-o	 ไม้",
"lili-o	 ดอกลิลลี่",
"lim-o	 เขต; senlima ไร้พรมแดน",
"limonad-o	 น้ำมะนาว",
"lingv-o	 ภาษา; lingvisto นักภาษาศาสตร์",
"lini-o	 เส้น",
"lip-o	 ริมฝีปาก",
"lit-o	 เตียงนอน; ellitiĝi ลุกจากเตียง; enlitiĝi ไปนอนบนเตียง",
"liter-o	 ตัวอักษร > alfabeto",
"litr-o	 ลิตร",
"liver-i	 (tr) ขน, ขนส่ง",
"log-i	 (tr) ล่อ, ดึงดูด; logo สิ่งล่อใจ, สิ่งน่าดึงดูด; allogi (tr) ล่อ, ดึงดูด",
"loĝ-i	 (ntr) อาศัยอยู่; loĝejo ที่อยู่อาศัย; transloĝiĝi (ntr) ย้ายที่อยู่",
"lok-o	 สถานที่",
"London-o	 กรุงลอนดอน",
"long-a	 ยาว",
"lu-i	 (tr) เช่า",
"lud-i	 (ntr) เล่น; ludema ขี้เล่น; ludilo ของเล่น; videoludo วิดีโอเกม",
"lukt-i	 (tr) สู้, ต่อสู้",
"lum-o	 แสงไฟ; lumi (ntr) ปล่อยแสง, เปล่งแสงออกมา",
"lun-o	 ดวงจันทร์",
"lund-o	 วันจันทร์",
"lup-o	 สุนัขป่า",
"M",
"maĉ-i	 (tr) เคี้ยว (สัตว์)",
"magazen-o	 ห้างสรรพสินค้า",
"magi-o	 มายากล; magiisto นักมายากล",
"magistr-o	 ปริญญาโท",
"magnet-o	 แม่เหล็ก",
"Maj-o	 เดือนพฤษภาคม",
"majest-a	 สง่าผ่าเผย, มีราศรี",
"majstr-o	 อาจารย์, มาสเตอร์",
"makul-o	 จุดตำหนิ",
"majuskl-o	 ตัวพิมพ์ใหญ่  > minusklo",
"mal- 	 (pre)	 พยางค์เติมหน้าแสดงถึงความหมายตรงกันข้าม: malbona ไม่ดี, ชั่ว; malbena ไม่สวย, น่าเกลียด",
"malgraŭ ทั้ง ๆ ที่, ถึงแม้ว่า > kvankam",
"malic-a	 ใจร้าย",
"mam-o	 เต้านม ",
"man-o	 มือ",
"manĝ-i	 (tr) กิน; matenmanĝo อาหารเช้า; tagmanĝo อาหารกลางวัน; formanĝi กินจนไม่เหลือ",
"manier-o	 วิธีการ; pensmaniero วิธีคิด",
"manik-o	 แขนเสื้อ",
"mank-i	 (ntr) ไม่มี, ขาด, ไร้: mankas vi al mi ผมคิดถึงคุณ",
"mantel-o	 เสื้อนอก, เสื้อโค้ท",
"mar-o	 ทะเล",
"mard-o	 วันอังคาร",
"mark-o	 สัญลักษณ์",
"marmelad-o	 ผลไม้กวน, แยมผลไม้",
"marŝ-i	 (ntr) เดินแถว, เดินผ่าน",
"Mart-o	 เดือนมีนาคม",
"martel-o	 ค้อน",
"mask-o	  หน้ากาก",
"mason-i	 (tr) ก่อ, สร้าง: <i>masoni muron</i> ก่อกำแพง",
"mastr-o	 อาจารย์, หัวโจก",
"maŝin-o	 เครื่องจักร",
"matematik-o	 คณิตศาสตร์",
"maten-o	 ตอนเช้า",
"matur-a	 สุก, บรรลุนิติภาวะ",
"mebl-o	 เฟอร์นิเจอร์",
"medi-o	 สิ่งแวดล้อม, สื่อ",
"medit-i	 (tr) ทำสมาธิ; medito, meditado การทำสมาธิ",
"mejl-o	 ไมล์",
"mem 	 (adv)	 ด้วยตัวเอง",
"membr-o	 สมาชิก",
"memor-i	 (x) จำได้, จำ; memoraĵo ของที่ระลึก; memorinda น่าจดจำ",
"menci-i	 (tr) กล่าวถึง, อ้าง > citi",
"mend-i	 (tr) จอง > rezervi; malmendi (tr) ยกเลิกจอง ",
"mens-o	 ความคิด",
"mensog-i	 (ntr) โกหก; mensogo คำโกหก",
"menton-o	 คาง",
"merit-i	 (tr) สมควรได้รับ; merito บุญ",
"merkred-o	 วันพุธ",
"met-i	 (tr) วาง; enmeti (tr) วางใน; demeti (tr) ถอดออก, วาง (ไข่); kunmeti (tr) วางให้อยู่ด้วยกัน; surmeti (tr) สวม (เสื้อผ้า)",
"metal-o	 โลหะ",
"meti-o	 งานฝีมือ",
"mev-o	 นกนางนวล",
"mez-o	 กลาง",
"mezur-i	 (tr) วัด (บางอย่าง); mezurilo เครื่องวัด",
"mi 	 (pro)	 ฉัน, ผม, ดิฉัน; mia ของฉัน, ของผม, ของดิฉัน",
"miel-o	 น้ำผึ้ง",
"mien-o	 สีหน้า",
"migr-i	 (ntr) ย้ายถิ่นที่อยู่อาศัย; enmigri อพยพเข้า; elmigri อพยพออก",
"miks-i	 (tr) ผสม",
"mil 	หนึ่งพัน",
"mild-a	 อ่อนโยน, นิ่มนวล",
"milion-o	 หนึ่งล้าน",
"milit-i	 (ntr) ทำสงคราม; milito สงคราม",
"minac-i	 (tr) ขู่",
"minus 	 (kon)	 ลบ",
"minuskl-o	 ตัวพิมพ์เล็ก > majusklo",
"minut-o	 นาที",
"mir-i	 (x) อัศจรรย์; mirinda น่าอัศจรรย์",
"misi-o	 ภารกิจ, หน้าที่ที่ได้รับมอบหมาย",
"mizer-o	 ความทุกข์ยาก, ความเศร้าโศก",
"moder-a	 พอเหมาะ, พอดี",
"modern-a	 สมัยใหม่, ทันสมัย",
"modest-a	 ถ่อมตัว > humila",
"mojos-a	 แจ๋ง, แจ๋ว",
"mok-i	 (tr) ล้อเลียน",
"mol-a	 นิ่ม, อ่อนโยน",
"moment-o	 ช่วงเวลาหนึ่ง, ช่วงเวลาครู่หนึ่ง",
"mon-o	 เงิน; monujo กระเป๋าสตางต์",
"monaĥ-o	 พระ; monaĥejo กุฏิ; monaĥino แม่ชี",
"monat-o	 เดือน; ĉiumonate ทุกเดือน; monataĵo ประจำเดือน = menstruoj",
"mond-o	 โลก; tutmonda ทั่วโลก",
"monstr-o	 ปีศาจ",
"mont-o	 ภูเขา; montaro เทือกเขา",
"montr-i	 (tr) แสดง, โชว์",
"mor-o	 วิถีชีวิต",
"mord-i	 (tr) กัด",
"morgaŭ	 (adv) พรุ่งนี้",
"mort-i	 (ntr) ตาย; mortigi  (tr) ฆ่า; mortinto ผู้ตาย, คนตาย",
"moŝt-o	 ฝ่าบาท (คำนำหน้าชื่อแสดงเกียรติของชนชั้นสูง)",
"motiv-o	 แรงจูงใจ; motivigi จูงใจ",
"mov-i	 (tr) เคลื่อนที่ (บางอย่าง); moviĝi เคลื่อนที่",
"muel-i	 (tr) โม่, บด",
"muĝ-i	(ntr) มอ ๆ (วัวร้อง)",
"mult-a	, mult-e	(da) (จำนวน) มาก",
"mur-o	 ฝาผนัง, กำแพง",
"murd-i	 (tr) ฆาตกรรม; murdisto ฆาตกร",
"murmur-i	 (ntr) พูดพึมพำ",
"mus-o	 หนู",
"musk-o	 มอส",
"mustard-o	 มัสตาร์ด",
"muŝ-o	 แมลงวัน",
"mut-a	 เป็นใบ้",
"muze-o	 พิพิธภัณฑ์",
"muzik-o	 ดนตรี; muzikilo เครื่องดนตรี; muzikisto นักดนตรี",
"N",
"-n	 (fin)	 ตัวลงท้ายใช้แสดงกรรมตรง แสดงการเคลื่อนที่เข้าไป, แทน je, แทน al",
"naci-o	 ชาติ; nacieco สัญชาติ; sennacieca ไร้สัญชาติ",
"naĝ-i	 (ntr) ว่ายน้า",
"najbar-o	 เพื่อนบ้าน",
"najl-o	 ตะปู",
"najtingal-o	 นก",
"nask-i	 (tr) ให้กำเนิด; naskiĝi (ntr)เกิด, กำเนิด",
"natur-o	 ธรรมชาติ",
"naŭ 	เก้า; naŭa ลำดับที่เก้า",
"naŭz-i	 (tr) ทำให้...อยากอาเจียน",
"naz-o	 จมูก",
"ne	 ไม่, ไม่ใช่ > nek",
"nebul-o	 หมอก",
"neces-a	 จำเป็น > bezoni",
"neĝ-o	 หิมะ; neĝi (ntr) หิมะตก",
"nek…  nek 	 (kon)	 ไม่...  และไม่",
"neni-a (adj) ไม่มีชนิดใดเลย",
"nenial 	 (adv)	 ไม่มีสักเหตุผล",
"neniam 	 (adv)	 ไม่เคย",
"nenie 	 (adv)	 ไม่มีที่ไหนเลย, ไม่มีสักที่",
"neniel 	 (adv)	 ไม่มีสักวิธีเลย",
"nenies 	 (pro)	 ไม่เป็นของใครเลย",
"nenio 	 (pro)	 ไม่มีสิ่งใด",
"neniu 	 (pro)	 ไม่มีใครเลย, ไม่มีสิ่งใดเลย; (adj) ไม่ใช่สัก...",
"nep-o	 หลานชาย (ลูกชายของลูก)",
"nepr-e	 จริงแท้, แน่นอน",
"nest-o	 รังนก",
"neŭtral-a	 มีความเป็นกลาง, เป็นกลาง",
"nev-o	 หลานชาย (ลูกชายของพี่หรือน้อง)",
"ni 	 (pro)	 พวกเรา; nia ของพวกเรา",
"nigr-a	 สีดำ",
"nivel-o	 ระดับ",
"-nj-	 (suf) พยางค์เติมท้ายแสดงรูปแบบของชื่อเล่นเพศหญิง:",
"nobel-o	 ชนชั้นสูง",
"nobl-a	 มีศีลธรรม",
"nokt-o	 กลางคืน",
"nom-o	 ชื่อ; nomi (tr) ตั้งชื่อ; nomiĝi (ntr) มีชื่อว่า; nomumi (tr) เสนอชื่อ",
"nombr-o	 จำนวน; nombri",
"nord-o	 ทิศเหนือ",
"not-o	 บันทึกโน้ต, โน้ตดนตรี",
"nov-a	 ใหม่; denove อีกครั้ง",
"Novembr-o	 เดือนพฤศจิกายน",
"nu 	 (int)	 ดีละ!, ถ้าอย่างนั้น!",
"nub-o	 เมฆ; nuba ครึ้มเมฆ",
"nud-a	 เปลือย",
"nuks-o	 ถั่ว",
"nul จำนวนศูนย์",
"nun เดี๋ยวนี้, ตอนนี้",
"nur 	 (adv)	 เท่านั้น, เพียงแต่",
"nutr-i	 (tr) ให้อาหาร, หล่อเลี้ยง",
"O",
"-o		 (fin)	 ตัวลงท้ายของคำนาม",
"obe-i	 (x) เชื่อฟัง; obeema ว่านอนสอนง่าย; malobeema ดื้อ",
"objekt-o	 วัตถุ, สิ่งของ",
"-obl- 	(suf) พยางค์เติมท้ายแสดงถึงการเพิ่มทวีคูณ: duobla สองเท่า",
"oblikv-a	 ลาดเอียง",
"observ-i	 (tr) สังเกตดู",
"obstin-a	 ดื่อดึง",
"odor-o	 กลิ่น",
"ofend-i	 (tr) เหยียดหยาม, ดูหมิ่น",
"ofer-i	 (tr) ถวาย, บูชา",
"ofert-i	 (tr) เสนอ (ขาย)",
"ofic-o	 งานออฟฟิศ; oficejo ออฟฟิศ, สำนักงาน",
"oft-a	 บ่อย ๆ, ประจำ",
"ok 	แปด; oka ที่แปด",
"okaz-i	 (ntr) เกิดขึ้น, ปรากฏขึ้น (เหตุการณ์)",
"okcident-o	 ทิศตะวันตก",
"Oktobr-o	 เดือนตุลาคม",
"okul-o	 ดวงตา",
"okup-i	 (tr) ยุ่งอยู่, สาละวนอยู่กับ",
"ol 	 (kon)	 กว่า (ในการเปรียบเทียบ)",
"ole-o	 น้ำมัน",
"ombr-o	 เงา, ร่มเงา",
"ombrel-o	 ร่ม",
"-on-	 (suf) พยางค์เติมท้ายแสดงถึงการเป็นเศษส่วน; duono หนึ่งส่วนสอง, ครึ่ง",
"ond-o	 คลื่น",
"oni 	 (pro)	 คนใดคนหนึ่ง หรือคนทั่วไป, ใคร ๆ, เขา, พวกเขา (คำสรรพนามไม่ชี้เฉพาะเจาะจง)",
"onkl-o	 ลุง, อา; onklino ป้า, น้า",
"-ont-	 (suf) พยางค์ท้ายของคำที่แสดงลักษณะของกริยาที่เกิดขึ้นในอนาคต",
"-op-	 (suf) พยางค์เติมแสดงถึงการจัดหมวดหมู่เกี่ยวกับตัวเลข",
"opini-i	 (tr) มีความเห็นต่อ; opinio ความเห็น",
"oportun-a	 สะดวก",
"or-o	 ทอง",
"oranĝ-o	 ส้ม",
"ord-o	 ระเบียบ, ลำดับ; ordigi จัดระเบียบ",
"ordinar-a	 ปกติทั่วไป",
"ordon-i	 (tr) สั่ง; ordono คำสั่ง",
"orel-o	 หู",
"orf-o	 เด็กกำพร้า",
"organ-o	 อวัยวะ",
"organiz-i	 (tr) จัด, organizaĵo, organizo องค์กร, องค์การ",
"orgen-o	 ออร์แกน (เครื่องดนตรี)",
"orient-o	 ทิศตะวันออก",
"ornam-i	 (tr) ตกแต่ง",
"-os	 (suf) ตัวลงท้ายของกริยารูปอนาคตกาล (จะ...)",
"osced-i	 (ntr) หาว",
"ost-o	 กระดูก",
"ostr-o	 หอยนางรม",
"-ot-	 (suf) พยางค์เติมท้ายแสดงลักษณะของกริยาที่จะถูกกระทำ",
"ov-o	 ไข่",
"P",
"pac-o	 สันติภาพ",
"pacienc-o	 ความอดทน",
"paf-i	 (tr) ยิง (ปืน); pafilo ปืน",
"pag-i	 (tr) จ่ายเงิน; senpaga ฟรี",
"paĝ-o	 หน้าในหนังสือ; retpaĝo เว็บเพจ",
"pajl-o	 ซาง (ปล้องของพืช)",
"pak-i	 (tr) ห่อ; malpaki (tr) แกะห่อ; pakaĵo พัสดุ, สิ่งของที่ถูกห่อ",
"pal-a	 ซีด",
"palac-o	 วัง",
"palp-i	 (tr) คลำ",
"palpebr-o	 หนังตา",
"pan-o	 ขนมปัง",
"pantalon-o	 กางเกงขายาว",
"pantofl-o	 รองเท้าสวมในบ้าน",
"pap-o	 พระสันตปาปา",
"paper-o	 กระดาษ",
"papili-o	 ผีเสื้อ",
"par-o	 คู่",
"pardon-i	 (x) ขอโทษ",
"parenc-o	 ญาติ",
"Pariz-o	 กรุงปารีส",
"parker-e	 จำจดขึ้นใจ",
"parol-i	 (tr) พูด, พูดภาษา; parolilo ไมค์",
"part-o	 ส่วน",
"parti-o	 พรรคพวก, กลุ่มคน",
"pas-i	 (ntr) ผ่าน; preterpasi (tr) ผ่าน, เลย",
"pasi-o	 ความมุ่งมั่น, ความรักอันแรงกล้า",
"Pask-o	 ปัสกา",
"pastr-o	 พระ",
"paŝ-i	 (ntr) ก้าว",
"paŝt-i	 (tr) พาไปกินหญ้า; <i>ŝafoj paŝtas sin</i> แกะไปกินหญ้า",
"patr-o	 พ่อ",
"pav-o	 นกยูง",
"pec-o	 ชิ้น",
"pejzaĝ-o	 ทิวทัศน์",
"pek-i	 (ntr) ทำบาป; peko บาป; pekulo คนบาป",
"pel-i	 (tr) ต้อน, ไล่; forpeli (tr) ไล่, ไล่...ไปให้พ้น",
"pen-i	 (ntr) ลอง, พยายาม (อย่างมาก) > provi, klopodi",
"pend-i	 (ntr) ถูกแขวน, แขวน; dependi ขึ้นอยู่กับ; sendependa อิสระ, ไม่ขึ้นกับใคร ",
"penetr-i	 (x) ทะลุ, ทะลวง",
"penik-o	 ผู่กัน",
"penis-o	 อวัยวะเพศชาย",
"pens-i	 (ntr) คิด; pensiga ทำให้คิด; penso ความคิด",
"pensi-o	 เงินบำนาญ",
"pent-i	 (x) สำนึกผิด, เสียใจต่อการกระผิด ",
"pentr-i	 (tr) วาดรูประบายสี",
"pep-i	 (ntr) ส่งเสียงร้องเล็ก ๆ ",
"per, pere (de) 	 (prep)	 โดย (เครื่องมือหรือสิ่งที่มาช่วยเหลือ)",
"percept-i	 (tr) รับรู้, สัมผัส",
"perd-i	 (tr) ทำหาย, หลง; perdiĝi หาย",
"pere-i	 (ntr) ตายโหง",
"perfekt-a	 สมบูรณ์แบบ",
"perfid-i	 (tr) ทรยศ, หลักหลัง",
"perl-o	 หอยมุก",
"permes-i	 (tr) อนุญาต; permesilo ใบอนุญาต",
"persekut-i	 (tr) ตามไล่ล่า",
"persik-o	 ลูกท้อ",
"persist-i	 (ntr) ยืนกราน, เพียรพยายาม, ไม่ย่อท้อ, (f) ดำเนินต่อเนื่องอย่างยาวนาน; persistema ยืดติด, เซ้าซี้, มากไปจนน่ารำคาญ",
"person-o	 บุคคล",
"persvad-i	 (x) โน้มนาว, ชักชวน",
"pes-i	 (tr) ชั่ง; pesilo ตาชั่ง, กิโล",
"pet-i	 (tr) ขอร้อง",
"petol-i	 (ntr) ร่าเริงอย่างเด็ก",
"pez-i	 (ntr) หนัก, มีน้ำหนัก",
"pi-a	 เคร่งศาสนา; piulo คนเคร่งสาศนา",
"pied-o	 เท้า",
"pig-o	 นกกางเขน",
"pik-i	 (tr) ทิ่ม; pika เจ็บ, แสบ, เผ็ด",
"pilk-o	 ลูกบอล; piedpilko ฟุตบอล",
"pinĉ-i	 (tr) คีบ, หนีบ; pinĉilo คีม, ตัวหนีบ",
"pingl-o	 เข็มกลัด",
"pint-o	 ยอด, จุดสูงสุด",
"pip-o	 กล้องยาสูบ",
"pipr-o	 พริกไทย",
"pir-o	 ลูกแพร์",
"pist-i	 (tr) ตำ, บด; pistilo สาก; pistujo ครก",
"piz-o	 ถั่ว (ตระกูลถั่วลันเตา); ĝardena pizo ถั่วลันเตา",
"plac-o	 สถานที่",
"plaĉ-i	 (ntr) เป็นที่พอใจ, ชอบ, ต้องใจ > ŝati",
"plad-o	 จานใบใหญ่",
"plafon-o	 เพดาน",
"plaĝ-o	 ชายหาด",
"pland-o	 ฝ่าเท้า",
"planed-o	 ดาวเคราะห์",
"plank-o	 พื้น",
"plant-o	 พืช; planti (tr) ปลูก",
"plat-a	 แบนราบ",
"plej 	 (adv)	 มากที่สุด",
"plekt-i	 (tr) ถัก, สาน",
"plen-a	 เต็ม",
"plend-i	 (ntr) ร้องทุกข์, บ่น",
"plezur-o	 ความยินดี, ความเต็มใจ",
"pli 	 (adv)	 มากกว่า",
"plor-i	 (ntr) ร้องไห้",
"plu 	 (adv)	 มากขึ้น, เพิ่มมากกว่าเดิม",
"plum-o	 ปากกา, ขนนก",
"plus 	 (kon)	 บวก",
"pluv-i	 (ntr) ฝนตก; pluvo ฝน",
"po คนละ, อันละ, ต่อ <i>La patrino donis al infanoj po du pomoj</i> แม่ให้แอปเปิ้ลเด็ก ๆ คนละสองลูก",
"poent-o	 จุด, คะแนน",
"polic-o	 กองตำรวจ; policano/policisto ตำรวจ; policejo สถานีตำรวจ",
"polus-o	 ขั้วโลก",
"polv-o	 ฝุ่น",
"pom-o	 แอปเปิล; terpomo มันฝรั่ง",
"pont-o	 สะพาน",
"popol-o	 ประชากร",
"por 	 (prep)	 เพื่อ; por ke ...u เพื่อที่ว่า",
"pord-o	 ประตู",
"pork-o	 สุกร, หมู; porkaĵo เนื้อหมู",
"port-i	 (tr) ถือ, ขน, บรรทุก; elporti (tr) เอา...ออกมา, (f) อดทนต่อ...จนถึงที่สุด; kunport-i	 นำมาด้วย;",
"posed-i	 (tr) เป็นเจ้าของ; posedanto เจ้าของ",
"post 	 (prep)	 ข้างหลัง, หลักจาก",
"postul-i	 (tr) ต้องการ, ต้องมี",
"poŝ-o	 กระเป๋าเสื้อ, กระเป๋ากางเกง, (f) กระเป๋าเงิน",
"poŝt-o	 การไปรษณีย์; poŝtmarko ดวงตราไปรษณีย์",
"potenc-o	 พลัง, อำนาจ",
"pov-i	 (tr) สามารถ; ĉiopova สามารถทุกทาง; daŭripovo, daŭropovo ความยั่งยืน",
"pram-o	 เรือข้ามฝ้าก",
"prav-i	 (ntr) แท้จริง, ถูกต้อง",
"precip-e	 เป็นหลัก, เป็นส่วนใหญ่",
"preciz-a	 เฉพาะ, เจาะจง",
"prefer-i	 (tr) ชอบ...มากกว่า",
"preĝ-i	 (ntr)อธิฐาน, สวดมนต์; preĝejo โบสถ์",
"prem-i	 (tr) กด, กดดัน",
"pren-i	 (tr) เอา, นำเอา, เอาไป",
"prepar-i	 (tr) เตรียม",
"pres-i	 (tr) พิมพ์; presejo โรงพิมพ์",
"preskaŭ 	 (adv)	 เกือบจะ",
"pret-a	 พร้อม",
"pretend-i	 (x) ยืนยันสิทธิ์",
"preter 	 (prep)	 ผ่าน",
"prez-o	 ราคา > kosto",
"prezent-i	 (tr) นำเสนอ",
"pri 	 (prep)	 เกี่ยวกับ",
"printemp-o	 ฤดูใบไม้ร่วง",
"pro 	 (prep)	 เนื่องจาก",
"problem-o	 ปัญหา",
"profund-a	 ลึก",
"progres-i	 (ntr) พัฒนาขึ้น",
"prokrast-i	 (tr) ผลัด, เลื่อน",
"proksim-a	 ใกล้; malproksima ไกล",
"prolet-o	 กรรมกร; proletaro ชนชั้นกรรมาชีพ (กลุ่มคน)",
"promen-i	 (ntr) เดินเล่น",
"promes-i	 (tr) สัญญา",
"prononc-i	 (tr) ออกเสียง = elparoli",
"propon-i	 (tr) เสนอ; propono ข้อเสนอ",
"propr-a	 ของตัวเอง",
"prosper-i	 (ntr) เจริญก้าวหน้า",
"protest-i	 (tr) ประท้วง; prostesto การประท้วง, คำประท้วง",
"prov-i	 (tr) ลอง, ทดสอบ > peni, klopodi",
"proverb-o	 สุภาษิต",
"proviz-i	 (tr) จัดเตรียม...เท่าที่มี",
"provizor-a 	ชั่วคราว, เฉพาะกาล",
"prudent-a	 ชาญฉลาด, ลุ่มลึก, รอบคอบ",
"prun-o	 ลูกพลัม",
"prunt-i	 (tr) ยืม",
"publik-a	 สาธารณะ; publikigi เผยแพร่...ต่อสาธารณะ",
"pugn-o	 กำปั้น",
"pulm-o	 ปอด",
"pulover-o	 เสื้อกันหนาวไหมพรมสวมทางศีรษะ",
"pulv-o	 ดินปืน",
"pulvor-o	 ผง",
"pun-i	 (tr) ลงโทษ; puno การสงโทษ; monpuno โทษปรับ",
"punkt-o	 จุด",
"pup-o	 ตุ๊กตา",
"pur-a	 สะอาด; purigi ทำให้...สะอาด, ทำความสะอาด",
"puŝ-i	 (tr) ผลัก, ดัน",
"put-o	 บ่อน้ำบาดาล",
"putr-i	 (tr) เน่า",
"R",
"rab-i	 (tr) ขโมย > ŝteli",
"rabat-o	 ส่วนลด",
"rad-o	 ล้อรถ",
"radi-o	 รังสี, สถานีวิทยุ; radioaparato เครื่องรับวิทยุ",
"radik-o	 ราก, รากศัพท์",
"rajd-i	 (tr) ขี่",
"rajt-o	 สิทธิ; rajti (tr) มีสิทธิ",
"rakont-i	 (tr) เล่า, บอก rakonto เรื่องเล่า",
"ramp-i	 (ntr) เลื้อย",
"ran-o	 กบ",
"rapid-a	 เร็ว; rapideco ความเร็ว",
"raport-i	 (x) รายงาน; raporto รายงาน; raportisto ผู้รายงาน",
"rast-i	 (tr) คราด; rastilo คราด",
"rat-o	 หนูบ้าน",
"raŭk-a	 เสียงแหบ",
"rav-i	 (tr) ทำให้...ลุ่มหลง",
"raz-i	 (tr) โกน; razilo มีดโกน",
"re- 	 (pre)	 พยางค์เติมหน้าเพื่อแสดงถึงการทำซ้ำหรือการย้อนกลับไปอีกครั้ง: reveni กลับมา; relerni เรียนอีกครั้ง",
"reciprok-a	 เท่ากัน, เสมอกัน",
"redakt-i	 (tr) แก้ไข; redaktisto บรรณาธิการ",
"reg-i	 (ntr) มีอำนาจ, (tr) ควบคุม, ปกครอง; registaro รัฐบาล",
"regal-i	 (tr) เลี้ยง (อาหาร)",
"regn-o	 อาณาจักร",
"regul-o	 กฎ",
"reĝ-o	 ราชา, กษัตริย์; reĝino ราชินี",
"reklam-i	 (tr) โฆษณา; reklamo โฆษณา",
"rekomend-i	 (tr) แนะนำ > sugesti",
"rekompenc-i	 (tr) ตอบแทน, ให้",
"rekt-a	 โดยตรง, ทางตรง",
"rel-o	 รางรถไฟ ",
"rem-i	 พายเรือ; remilo ไม้พาย",
"ren-o	 ไต",
"renkont-i	 (tr) พบเจอ (บางอย่าง); renkontiĝi kun นัดพบเจอกับ, พบเจอกับ",
"renvers-i	 (tr) ทำให้...ล้ม, พัง",
"respond-i	 (tr) ตอบ; respondo คำตอบ",
"rest-i	 (ntr) พักอาศัย; restejo สถานที่พักอาศัย",
"restoraci-o	 ภัตตาคาร, ร้านอาหาร",
"ret-o	 ตาข่าย; interreto อินเตอร์เน็ต",
"rev-i	 (x) ฝัน, ใฝ่ฝัน > sonĝi; revo ความใฝ่ฝัน",
"rezerv-i	 (tr) จอง > mendi",
"rezign-i	 (x) ล้มเลิก",
"rezist-i	 (tr) ต้านทาน",
"rezult-o	 ผล",
"ribel-i	 (ntr) ไม่เชื่อฟัง, กบฏ",
"ricev-i	 (tr) รับ, ได้รับ > akiri, gajni",
"riĉ-a	 รวย; riĉulo คนรวย, เศรษฐี",
"rid-i	 (ntr) หัวเราะ; rideti ยิ้ม",
"rifuĝ-i	 (ntr) หลบหนี, ลี้ภัย; rifuĝinto ผู้ลี้ภัย",
"rifuz-i	 (tr) ปฏิเสธ",
"rigard-i	 (tr) ดู, มอง",
"rigid-a	 แข็ง, กระด้าง",
"rigor-a	 เคร่งครัด, ไร้เมตตา > severa",
"rikolt-i	 (tr) เก็บเกี่ยว",
"rilat-i	 (ntr) มีความสัมพันธ์; rilato ความสัมพันธ์",
"rim-o	 การสัมผัสในบทกลอน",
"rimark-i	 (tr) สังเกต",
"rimed-o	 ทรัพยากร, แหล่งข้อมูล",
"ripet-i	 (tr) ทำซ้ำ, ทำ...อีกรอบ",
"ripoz-i	 (ntr) พักผ่อน; ripozejo สถานที่พักผ่อน",
"riproĉ-i	 (tr) ตำหนิ",
"risk-i	 (tr) เสี่ยง",
"rit-o	 พิธีกรรม",
"river-o	 แม่น้ำ",
"riz-o	 ข้าว",
"rob-o	 ชุดยาวของผู้หญิง",
"rok-o	 หินก้อนใหญ่",
"roman-o	 นวนิยาย",
"romp-i	 (tr) ทำพัง, ทำเสียหาย; interrompi ขัดขวาง, ขัดจังหวะ (เวลาพูด)",
"rond-o	 วงกลม, กลุ่มทำกิจกรรม",
"ronk-i	 (ntr) กรน",
"rost-i	 (tr) ปิ้ง, ย่าง",
"roz-o	 ดอกกุหลาบ",
"ruband-o	 ริบบิ้น",
"ruĝa สีแดง",
"rul-i	 (tr) กลิ้ง",
"rust-o	 สนิม; rustiĝi เป็นสนิม",
"ruz-a	 เจ้าเล่ห์",
"S",
"sabat-o	 วันเสาร์",
"sabl-o	 ทราย; sablero เม็ดทราย",
"sabr-o	 ดาบใหญ่",
"sag-o	 ลูกศร",
"saĝ-a	 เฉลียวฉลาด, มีปัญญา",
"sak-o	 ถุง; dorsosako กระเป๋าเป้; mansako กระเป๋าถือ",
"sal-o	 เกลือ",
"salajr-o	 เงินเดือน; salajrulo มนุษย์เงินเดือน",
"saliv-o	 น้ำลาย",
"salm-o	 ปลาแซลมอน",
"salt-i	 (ntr) กระโดด",
"salut-i	 (tr) ทักทาย: Saluton! สวัสดี",
"sam-a	 เหมือนกัน; malsama แตกต่าง",
"san-a	 สุขภาพดี, สุขภาพปกติ; malsana ไม่สบาย; malsanulejo โรงพยาบาล = hospitalo",
"sandviĉ-o	 แซนด์วิช",
"sang-o	 เลือด",
"sankt-a	 ศักดิ์สิทธิ์; sanktulo นักบุญ",
"sap-o	 สบู่",
"sat-a	 อิ่ม; malsata หิว",
"saŭc-o	 ซอส",
"sav-i	 (tr) ช่วยชีวิต, รักษาชีวิต",
"sci-i	 (tr) รู้",
"scienc-o	 วิทยาศาสตร์",
"se 	 (kon)	 ถ้า",
"sed 	 (kon)	 แต่",
"seg-i	 (tr) เลื่อย; segilo เลื่อย",
"seĝ-o	 เก้าอี้",
"sek-a	 แห้ง; malseka เปียก",
"sekret-a	 เป็นความลับ, ลับ; sekreto ความลับ",
"seks-o	 เพศ; seksumo เพศสัมพันธ์",
"sekund-o	 วินาที",
"sekv-i	 (tr) ติดตาม; sekvanto ผู้ติดตาม",
"sel-o	 อาน",
"selekt-i	 (tr) คัดเลือก > elekti",
"sem-i	 (tr) หว่านเมล็ด; semo เมล็ด",
"semajn-o	 สัปดาห์",
"sen 	 (prep)	 ปราศจาก",
"senc-o	 ความหมาย, ลักษณะการใช้ (คำ, ถ้อยคำ)",
"send-i	 (tr) ส่ง",
"sens-o	 ความรู้สึก = sentumo",
"sent-i	 (tr) รู้สึก <i>Mi sentas min feliĉa.</i> ผมรู้สึกว่าผมมีความสุข; sentema ความรู้สึกอ่อนไหว; sentumo ความรู้สึก = senso",
"sep 	เจ็ด sepa ที่เจ็ด",
"Septembr-o	 เดือนกันยายน",
"serĉ-i	 (tr) ค้นหา, มองหา",
"seren-a	 เงียบสงบ",
"seri-o	 ลำดับ, ชุด",
"serioz-a	 เครียด, จริงจัง",
"serpent-o	 งู",
"serur-o	 ลูกบิดประตู",
"serv-i	 (tr) บริการ; servo การบริการ",
"ses 	หก sesa ที่หก",
"sever-a	 เคร่งครัด, เคร่ง > rigora",
"sezon-o	 ฤดูกาล",
"si 	 (pro)	 เขาเอง, หล่อนเอง, มันเอง, พวกมันเอง (สรรพนามสะท้อนบุรุษที่ 3 เอกพจน์หรือพหูพจน์); sia ของเขาเอง, ของหล่อนเอง, ของมันเอง, ของพวกมันเอง",
"sid-i	 (ntr) นั่ง; sidiĝi (ntr) นั่งลง",
"sign-o	 สัญลักษณ์; demandsigno เครื่องหมายคำถาม (?); krisigno เครื่องหมายตกใจ (!)",
"signif-i	 (tr) หมายถึง, มีความหมาย; signifo ความหมาย",
"silab-o	 พยางค์",
"silent-i	 (ntr) เงียบ; silento ความเงียบ",
"silk-o	 ไหม",
"simi-o	 ลิง",
"simil-a	 คล้าย",
"simpl-a	 เรียบง่าย, ธรรมดา",
"sincer-a	 จริงใจ > honesta",
"sinjor-o	 นาย, สุภาพบุรุษ; sinjorino สุภาพสตรี",
"skatol-o	 กล่อง",
"skem-o	 แผน(อย่างคร่าว ๆ) > plano",
"ski-i	 (ntr) เล่นสกี; skio กีฬาสกี",
"skiz-o	 แบบร่าง",
"sklav-o	 ทาส",
"skrap-i	 (tr) ขูด",
"skrib-i	 (tr) เขียน; skribilo เครื่องเขียน (หนึ่งอย่าง)",
"sku-i	 (tr) เขย่า",
"skulpt-i	 (tr) ปั้น, สลัก, แกะ, หล่อ",
"skvam-o	 เกล็ด",
"sobr-a	 กินหรือดื่มอย่างพอดี, คอแข็ง, (f) อย่างผู้ดี",
"societ-o	 สมาคม (เล็ก), สโมสร",
"soif-i	 (ntr) กระหายน้ำ",
"sol-a	 โดดเดี่ยว: <i>lasu min sola</i> โปรดปล่อยให้ผมอยู่คนเดียว; sole อย่างเดียว, อย่างโดดเดี่ยว",
"soldat-o	 ทหาร",
"solen-a	 หรูหรา, ยิ่งใหญ่",
"solv-i	 (tr) แก้ไข",
"somer-o	 ฤดูร้อน",
"son-i	 (ntr) ส่งเสียง; sono เสียง",
"sonĝ-o	 ฝัน > revi",
"sonor-i	 (ntr) ส่งเสียงกริ๊ง ๆ, กังวาน; sonorilo ระฆัง",
"sopir-i	 (x) คิดถึง",
"sorĉ-i	 (tr) ใช้เวทมนต์; sorĉisto พ่อมด",
"sort-o	 วาสนา",
"sovaĝ-a	 ป่าเถื่อน",
"spac-o	 พื้นที่",
"spec-o	 ชนิด; ĉiuspeca = ĉia",
"spegul-o	 กระจก, คันฉ่อง; speguli (tr) สะท้อน",
"spekt-i	 (tr) ดู, ชม",
"spektakl-o	 การแสดง",
"spert-a	 มีประสบการณ์; spertulo ผู้มีประสบการณ์",
"spez-o	 การใช้เงิน, รายรับรายจ่าย; enspezo รายรับ; elspezo รายจ่าย",
"spin-o	 กระดูกสันหลัง",
"spinac-o	 ผักขม",
"spir-i	 (ntr) หายใจ; enspiri หายใจเข้า; elspiri หายใจออก",
"spirit-o	 จิตวิญญาณ, จิตใจ > animo",
"spit-i	 (tr) ท้าทาย",
"sprit-a	 มีไหวพริบ",
"staci-o	 สถานี",
"stal-o	 คอกสัตว์",
"stamp-i	 (tr) ประทับ, ประตราลงบน",
"stan-o	 ดีบุก",
"standard-o	 ธง > flago",
"stang-o	 ท่อนไม้",
"star-i	 (ntr) ยืน",
"stat-o	 สถานะ",
"statu-o	 รูปปั้น",
"stel-o	 ดวงดาว",
"step-o	 ที่ราบกว้างใหญ่ซึ่งไม่มีต้นไม้, ทุ่งหญ้าสเตป",
"sterk-o	 ปุ๋ย",
"stomak-o	 กระเพาะ",
"strang-a	 แปลก; strangulo คนแปลกหน้า",
"strat-o	 ถนน",
"streĉ-i	 (tr) ทำให้ตึง, แกร็ง",
"strek-o	 เครื่องหมายขีดยาว − ; streketo เครื่องหมายขีดสั้น -",
"stud-i	 (tr) ศึกษา; studo การศึกษา",
"student-o	 นิสิต, นักศึกษา",
"stult-a	 งี่เง่า, โง่; stultulo คนโง่",
"sub 	 (prep)	 ข้างใต้",
"subit-a	 กะทันหัน, ฉับพลัน > abrupta",
"suĉ-i	 (tr) ดูด",
"sud-o	 ทิศใต้",
"sufer-i	 (ntr) ทุกข์ทรมาน",
"sufiĉ-a	 พอ",
"sufok-i	 (tr) ทำให้...ขาดอากาศหายใจ (ตาย)",
"sugest-i	 (tr) แนะนำ, ให้ข้อเสนอ > rekomendi",
"suk-o	 น้ำผลไม้",
"sukces-i	 (ntr) สำเร็จ",
"suker-o	 น้ำตาล",
"sulk-o	 ร่อง; sulki (tr) ทำให้...เป็นร่อง",
"sun-o	 พระอาทิตย์",
"sup-o	 น้ำซุป",
"super 	 (prep)	 เหนือ",
"supoz-i	 (tr) คิดว่า",
"supr-a	 ด้านบน; malsupra ด้านล่าง",
"sur 	 (prep)	 บน",
"surd-a	 หูหนวก; surdulo คนหูหนวก",
"surpriz-i	 (tr) ทำให้...ประหลาดใจ; surpriziĝi รู้สึกประหลาดใจ",
"surtut-o	 เสื้อคลุม",
"suspekt-i	 สงสัย, คาดเดา > dubi",
"svarm-o	 ฝูง (คน/สัตว์)",
"sven-i	 (ntr) เป็นลม",
"sving-i	 (tr) แกว่ง",
"Ŝ",
"ŝaf-o	 แกะ",
"ŝajn-i	 (ntr) ดูเหมือนว่า",
"ŝanc-o	 โอกาส",
"ŝancel-i	 (tr) ทำให้...ล้ม, ทำให้...พังทลาย",
"ŝanĝ-i	 (tr) เปลี่ยน; interŝanĝi แลกเปลี่ยน",
"ŝarg-i	 (tr) เติม, บรรจุ; ŝargilo ที่ชาร์จ",
"ŝarĝ-i	 (tr) บรรทุก, ขน",
"ŝat-i	 (tr) ชอบ",
"ŝaŭm-o	 ฟอง",
"ŝel-o	 เปลือก; elŝeligi, senŝeligi ปลอกเปลือก",
"ŝelk-o	 สายดึงกางเกง",
"ŝerc-i	 (ntr) พูดตลก; ŝerco เรื่องตลก, มุขตลก",
"ŝi 	 (pro)	 เขา (ผู้หญิง); ŝia ของเขา (ผู้หญิง)",
"ŝild-o	 ป้ายเล็ก ๆ ",
"ŝink-o	 หมูแฮม",
"ŝip-o	 เรือ (ขนาดใหญ่) > boato",
"ŝir-i	 (tr) ฉีก",
"ŝirm-i	 (tr) บัง, บดบัง",
"ŝlos-i	 (tr) ใส่กุญแจ, ล็อก (ด้วยกุญแจ); ŝlosilo ลูกกุญแจ",
"ŝmink-i	 (tr) แต่งหน้า",
"ŝmir-i	 (tr) ทา, ละเลง",
"ŝnur-o	 เชือก",
"ŝose-o	 ถนนใหญ่",
"ŝovel-i	 (tr) ตัก; ŝovelilo ที่ตัก (เช่นที่ตักขยะ)",
"ŝpar-i	 (tr) ออม; ŝparema ประหยัด",
"ŝpruc-i	 (ntr) พ่นน้ำ",
"ŝrank-o	 ตู้ใส่ของ, ห้องเล็ก; tirŝranko ลิ้นชัก",
"ŝraŭb-o	 น็อตตัวผู้",
"ŝtal-o	 เหล็กกล้า",
"ŝtat-o	 รัฐ, เมือง",
"ŝtel-i	 (tr) ลัก, ขโมย > rabi",
"ŝtof-o	 ผ้า (เป็นชิ้น ๆ), วัสดุ",
"ŝton-o	 ก้อนหิน",
"ŝtop-i	 (tr) อุด",
"ŝtrump-o	 ถุงเท้า",
"ŝtup-o	 ขั้นบันได; ŝtuparo บันได",
"ŝu-o	 รองเท้า",
"ŝut-i	 (tr) เท (เฉพาะของที่ไม่ใช่ของเหลว); alŝuti, enŝuti เทเข้า, อัปโหลด; elŝuti เทออก, ดาว์นโหลด",
"ŝveb-i	 (ntr) ลอย  (อยู่อากาศ)",
"ŝvel-i	 (ntr) บวม, นูน",
"ŝvit-i	 (ntr) เหงื่อออก; ŝvito เหงื่อ",
"T",
"tabel-o	 ตาราง",
"tabl-o	 โต๊ะ",
"tabul-o	 กระดาน",
"tag-o	 วัน; tage ในเวลากลางวัน; ĉiutage ทุกวัน; naskiĝtago วันเกิด",
"taj-o	 กลุ่มชาติพันธุ์ไท, คนไทย; taja ไท, ไทย; Tajlando ประเทศไทย; tajlandano คนไทย",
"tajlor-o	 ช่างตัดเสื้อ",
"tajp-i	 (tr) พิมพ์; tajpilo พิมพ์ดีด",
"taks-i	 (tr) ประเมินค่า",
"taksi-o	 รถแท็กซี่",
"tambur-o	 กลอง",
"tamen 	 (kon)	 อย่างไรก็ตาม",
"tamtam-o	 กลองทอม",
"tapiŝ-o	 เสื่อ",
"tas-o	 แก้วดื่มน้ำ",
"task-o	 งาน, สิ่งที่ได้รับมอบหมายให้ทำ",
"taŭg-a	 เหมาะสม > deca",
"tavol-o	 ชั้น > etaĝo",
"te-o	 น้าชา",
"team-o	 ทีม",
"teatr-o	 โรงละคร",
"ted-i	 (tr) ทำให้...รู้สึกน่าเบื่อ > enui",
"tegment-o	 หลังคา",
"teler-o	 จาน",
"televid-o	 โทรทัศน์",
"temp-o	 เวลา",
"ten-i	 (tr) ถือ, รักษา, เก็บไว้; elteni อดทน",
"tend-o	 เต้นท์",
"tendenc-o	 แนวโน้ม",
"tenis-o	 เทนนิส",
"tent-i	 (tr) ล่อลวง, ชักนำไปในทางที่ผิด",
"ter-o	 แผ่นดิน, โลก",
"terur-o	  ความกลัว, ความน่าหวาดกลัว",
"tez-o	 วิทยานิพนธ์",
"tia (adj) เช่นนั้น, แบบนั้น",
"tial 	 (adv)	 ด้วยเหตุนั้น",
"tiam 	 (adv)	 เวลานั้น",
"tie 	 (adv)	 ที่นั้น; ĉi tie/tie ĉi ที่นี่",
"tiel 	 (adv)	 ด้วยวิธีนั้น",
"ties 	 (pro)	 ของคนนั้น, ของสิ่งนั้น",
"tigr-o	 เสือ ",
"tim-i	 (tr) กลัว; timo ความกลัว; timema ขี้กลัว",
"tio 	 (pro)	 สิ่งนั้น; ĉi tio/tio ĉi สิ่งนี้",
"tiom 	 (adv)	 จำนวนนั้น, ปริมาณนั้น",
"tip-o	 ชนิด, ประเภท",
"tir-i	 (tr) ดึง, ลาก; altiri (tr) ดึงไป, ลากไป",
"titol-o	 หัวเรื่อง, ชื่อเรื่อง, ไตเติ้ล",
"tiu 	 (pro)	 สิ่งนั้น, คนนั้น; (adj) ...นั้น; ĉi tiu/tiu ĉi 	 (pro)	 สิ่งนี้, คนนี้; (adj) ĉi tiu/tiu ĉi ...นี้;",
"tol-o	 ผ้าลินิน, ผ้าฝ้าย",
"toler-i	 (tr) อดทน, อดกลั้น > pacienco",
"tomat-o	 มะเขือเทศ",
"tomb-o	 หลุมฝังศพ; tombejo สุสาน; entombigi ฝัง (ศพ)",
"tond-i	 (tr) ตัด (ด้วยกรรไกร); tondilo กรรไกร",
"tondr-i	 (ntr) ฟ้าร้อง",
"torent-o	 กระแสน้ำ",
"tra 	 (prep)	 ทะลุผ่าน, ตลอด",
"tradici-o	 ประเพณีนิยม",
"traduk-i	 (tr) แปล; tradukisto นักแปล",
"traf-i	 (tr) ชน, ตี",
"trafik-o	 การจราจร",
"trajt-o	 แบบ, ลักษณะ",
"trakt-i	 (tr) จัดการ, ดำเนินการ",
"traktor-o	 รถแทรกเตอร์",
"tram-o	 รถราง",
"tranĉ-i	 (tr) ตัด (ด้วยมีด); tranĉilo มีด",
"trankvil-a	 สงบ, สบายใจ",
"trans 	 (prep)	 ข้าม",
"tre 	 (adv)	 มาก",
"trem-i	 (ntr) สั่น; tertremo แผ่นดินไหว > skui",
"tren-i	 (tr) ลาก",
"trezor-o	 สมบัติ",
"tri 	สาม; tria ที่สาม",
"trib-o	 ชนเผ่า > gento",
"trink-i	 (tr) ดื่ม; trinkaĵo เครื่องดื่ม; trinkejo ร้านเหล้า, บาร์",
"tro 	(adv)	มากเกินไป; troigo สิ่งเกินจริง",
"tromp-i	 (tr) หลอกลวง",
"trov-i	 (tr) พบ; troviĝi พบ, มี; eltrovi พบสิ่งที่ไม่เคยเจอมาก่อน",
"tru-o	 หลุม",
"trud-i	 (tr) บังคับ > devigi",
"trumpet-o	 ทรัมเป็ต",
"trunk-o	 ลำต้น, ลำตัว",
"tub-o	 ท่อ",
"tuj 	 (adv)	 ในทันใด, เดี๋ยวนี้",
"tuk-o	 ผ้า bantuko ผ้าขนหนู; tablotuko ผ้าปูโต๊ะ",
"tulip-o	 ดอกทิวลิป",
"tumor-o	 เนื้องอก",
"tun-o	 ตัน",
"tunel-o	 อุโมงค์",
"tur-o	 หอสูง, หอคอย",
"turism-o	 การท่องเที่ยว",
"turment-i	 (tr) ทรมาร, ทารุณกรรม",
"turn-i	 (tr) เลี้ยว, พลิก, หัน",
"tuŝ-i	 (tr) จับ; netuŝebla จับต้องไม่ได้",
"tut-o	 ทั้งหมด",
"U",
"-u	 (fin)	 ตัวลงท้ายกริยาแสดงคำสั่ง: <i>ni iru!<i/> พวกเราไปกันเถอะ; <i>skribu nun!<i/> เขียนเดี๋ยวนี้",
"-uj-	 (suf) พยางค์เติมท้ายเพื่อแสดงว่าเป็นภาชนะ ที่อยู่ของ ต้นไม้ หรือประเทศ <i>(แบบเก่า)</i>; paperujo ที่ใส่กระดาษ; abelujo รังผึ้ง; bananujo ต้นกล้วย; Anglujo ประเทศอังกฤษ",
"-ul-	 (suf) พยางค์เติมท้ายเพื่อระบุว่าเป็นบุคคล; riĉulo คนรวย, เศรษฐี; belulino สาวสวย",
"-um-	 (suf) พยางค์เติมท้ายที่ไม่มีความหมายที่จำกัดเป็นพิเศษ: brakumi กอด; plenumi ทำให้สมบูรณ์; umi (ntr) ทำอะไรบางอย่างที่บอกแน่นอนไม่ได้",
"ung-o	 เล็บ",
"unik-a	 หนึ่งเดียว",
"universal-a	 สากล",
"universitat-o	 มหาวิทยาลัย",
"unu	หนึ่ง; unua ที่หนึ่ง",
"urb-o	 เมือง; ĉefurbo เมืองหลวง",
"urĝ-a	 ด่วน, เร่งรีบ",
"urs-o	 หมี",
"-us	 (fin)	 ตัวลงท้ายกริยาที่อยู่ในประโยคแสดงเงื่อนไขหรือสมมติ",
"Uson-o	 สหรัฐอเมริกา; usonano ชาวอเมริกัน > Ameriko",
"util-a	 มีประโยชน์; utileco ความมีประโยชน์; utiligi (tr) ทำให้...เกิดประโยชน์",
"uz-i	 (tr) ใช้; uzebla ใช้ได้",
"Ŭ",
"ŭa! 	 (int)	 เสียงร้องของเด็กหรือสุนัข",
"ŭat-o	 วัตต์",
"V",
"vag-i	 (ntr) เดินทางอย่างไม่มีจุดหมาย",
"vagon-o	 ตู้รถไฟ; vagonaro ขบวนรถไฟ",
"vaks-o	 ขี้ผึ้ง",
"val-o	 หุบเขา",
"valid-a	 ยังใช้ได้",
"valiz-o	 กระเป๋าเดินทาง",
"valor-o	 คุณค่า; valori (ntr) มีคุณค่า",
"van-a	 ไร้ประโยชน์",
"vang-o	 แก้ม",
"vant-a	 ไร้สาระ, ไม่มีประโยชน์",
"vapor-o	 ไอน้ำ",
"var-o	 สินค้า, ผลิตภัณฑ์",
"varb-i	 (tr) ทำให้...เป็นสมาชิก (กลุ่ม, ชมรม, สมาคม), ทำให้...เป็นทหาร",
"varm-a	 ร้อน, อุ่น, อบอุ่น; malvarma เย็น, หนาว",
"vast-a	 ใหญ่มโหฬาร; disvastigi เผยแพร่",
"vaz-o	 แจกัน",
"ve! โธ่เอ้ย",
"vek-i	 (tr) ปลุก; vekiĝi ตื่น",
"ven-i	 (ntr) มา; alveni (ntr) มาถึง",
"vend-i	 (tr) ขาย; vendejo ร้านขายของ",
"vendred-o	 วันศุกร์",
"venen-o	 ยาพิษ",
"venĝ-i	 (x) แก้แค้น",
"vent-o	 ลม; ventumilo พัดลม",
"ventr-o	 ท้อง",
"ver-o	 ความจริง; vera จริง",
"verd-a	 สีเขียว",
"verk-i	 (tr) ประพันธ์, เขียน; verkisto นักประพันธ์, นักเขียน > aŭtoro",
"verm-o	 หนอน",
"verŝ-i	 (tr) เท (ของเหลว) > ŝuti",
"vesper-o	 ตอนเย็น",
"vest-o	 = vestaĵo เสื้อผ้า, ชุด; vesti (tr) สวมเสื้อให้ <i>ŝi vestas sin per tre bela vestaĵo</i> หล่อนสวมชุดที่สวยงามมาก",
"vet-i	 (tr) ผนัน; veto การผนัน",
"veter-o	 สภาพอากาศ",
"vetur-i	 (ntr) เดินทาง (ด้วยยานพาหนะ); veturilo ยานพาหนะ",
"vi 	 (pro)	 คุณ (สรรพนามบุรุษที่ 2 เอกพจน์) > ci, พวกคุณ (สรรพนามบุรุษที่ 2 พหูพจน์); via ของคุณ, ของพวกคุณ ",
"viand-o	 เนื้อสัตว์",
"vic-o	 แถว, เป็นลำดับ; vic- 	 (pre)	 รอง- vicprezidanto รองประธาน",
"vid-i	 (tr) มองเห็น; videbla มองเห็นได้",
"vidv-o	 พ่อหม้าย; vidvino แม่หม้าย",
"vigl-a	 ตื่นตัว, สดชื่น",
"vilaĝ-o	 หมู่บ้าน",
"vin-o	 ไวน์",
"vinagr-o	 น้ำส้มสายชู",
"vintr-o	 ฤดูหนาว",
"vir-o	 ผู้ชาย; virino ผู้หญิง",
"virt-o	 ศีลธรรม",
"viŝ-i	 (tr) เช็ด, ถู",
"vitr-o	 แก้ว (วัตถุ), กระจก",
"viv-o	 ชีวิต; vivi มีชีวิต",
"vizaĝ-o	 ใบหน้า",
"vizit-i	 (tr) มาหา, มาเยือน",
"vjetnam-o	 ชาวเวียดนาม; vjetnama  เวียดนาม; Vjetnamio ประเทศเวียดนาม",
"voĉ-o	 เสียง (พูด)",
"voj-o	 ถนน, ทางเดิน",
"vojaĝ-i	 (ntr) ท่องเที่ยว, เดินทาง; vojaĝanto นักท่องเที่ยว, นักเดินทาง",
"vok-i	 (tr) เรียก (ให้มา)",
"vol-i	 (tr) ต้องการ; bonvoli ได้โปรด, กรุณา",
"volont-e	 ด้วยความสมัครใจ; volonteco จิตอาสา; volontulo อาสาสมัคร",
"volum-o	 ฉบับ, ชุดหนังสือ",
"volumen-o	 ปริมาตร",
"volv-i	 (tr) พัน; disvolvi ขยาย...ออก, (f) เผยแพร่, พัฒนา",
"vom-i	 (tr) อาเจียน",
"vort-o	 คำศัพท์; vortaro พจนานุกรม; tabelvortoj คำตาราง (กลุ่มคำชนิดหนึ่งของภาษาเอสเปรันโตซึ่งมักจะเห็นได้ในรูปแบบของตาราง)",
"vost-o	 หาง",
"vulkan-o	 ภูเขาไฟ",
"vulp-o	 สุนัขจิ้งจอก",
"vund-i	 (tr) ทำให้...เกิดบาดแผล; vundo บาดแผล",
"Z",
"Zamenhof	ซาเมนฮอฟ (1859-1917) ผู้ประดิษฐ์ภาษาเอสเปรันโต; zamenhofeco ลักษณะของซาเมนฮอฟ, อัตลักษณ์ของซาเมนฮอฟ; zamenhofismo ซาเมนฮอฟนิยม (สำนวนภาษาของซาเมนฮอฟ)",
"zebr-o	 ม้าลาย",
"zelot-o	 ผู้คลั่งไคล้",
"zingibr-o	 ขิง",
"zo-o	 สวนสัตว์ = bestoĝardeno, zoologia ĝardeno",
"zon-o	 เข็มขัด, เขต; mamzono ยกทรง",
"zorg-i	 (tr) ดูแล, ใส่ใจ; zorganto ผู้ดูแล",
"zum-i	 (ntr) ทำเสียงหึ่ง ๆ, ฮัมเพลง",
];

